// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: contracts/runner/v1/runner.proto

package runnerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RunnerControl_Connect_FullMethodName = "/secondbox.runner.v1.RunnerControl/Connect"
)

// RunnerControlClient is the client API for RunnerControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RunnerControl is the single authenticated, runner-initiated control channel.
// The first messages MUST be RunnerHello and RunnerWelcome (or
// ProtocolRejection). No registration or mutation is valid before negotiation.
type RunnerControlClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RunnerToControlPlane, ControlPlaneToRunner], error)
}

type runnerControlClient struct {
	cc grpc.ClientConnInterface
}

func NewRunnerControlClient(cc grpc.ClientConnInterface) RunnerControlClient {
	return &runnerControlClient{cc}
}

func (c *runnerControlClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RunnerToControlPlane, ControlPlaneToRunner], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RunnerControl_ServiceDesc.Streams[0], RunnerControl_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunnerToControlPlane, ControlPlaneToRunner]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RunnerControl_ConnectClient = grpc.BidiStreamingClient[RunnerToControlPlane, ControlPlaneToRunner]

// RunnerControlServer is the server API for RunnerControl service.
// All implementations must embed UnimplementedRunnerControlServer
// for forward compatibility.
//
// RunnerControl is the single authenticated, runner-initiated control channel.
// The first messages MUST be RunnerHello and RunnerWelcome (or
// ProtocolRejection). No registration or mutation is valid before negotiation.
type RunnerControlServer interface {
	Connect(grpc.BidiStreamingServer[RunnerToControlPlane, ControlPlaneToRunner]) error
	mustEmbedUnimplementedRunnerControlServer()
}

// UnimplementedRunnerControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRunnerControlServer struct{}

func (UnimplementedRunnerControlServer) Connect(grpc.BidiStreamingServer[RunnerToControlPlane, ControlPlaneToRunner]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedRunnerControlServer) mustEmbedUnimplementedRunnerControlServer() {}
func (UnimplementedRunnerControlServer) testEmbeddedByValue()                       {}

// UnsafeRunnerControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunnerControlServer will
// result in compilation errors.
type UnsafeRunnerControlServer interface {
	mustEmbedUnimplementedRunnerControlServer()
}

func RegisterRunnerControlServer(s grpc.ServiceRegistrar, srv RunnerControlServer) {
	// If the following call panics, it indicates UnimplementedRunnerControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RunnerControl_ServiceDesc, srv)
}

func _RunnerControl_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RunnerControlServer).Connect(&grpc.GenericServerStream[RunnerToControlPlane, ControlPlaneToRunner]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RunnerControl_ConnectServer = grpc.BidiStreamingServer[RunnerToControlPlane, ControlPlaneToRunner]

// RunnerControl_ServiceDesc is the grpc.ServiceDesc for RunnerControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RunnerControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "secondbox.runner.v1.RunnerControl",
	HandlerType: (*RunnerControlServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _RunnerControl_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "contracts/runner/v1/runner.proto",
}
