// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: microsandbox-helper/v1/helper.proto

package microsandboxprotocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operation int32

const (
	Operation_OPERATION_UNSPECIFIED      Operation = 0
	Operation_OPERATION_START            Operation = 1
	Operation_OPERATION_EXEC             Operation = 2
	Operation_OPERATION_FILE_READ        Operation = 3
	Operation_OPERATION_FILE_WRITE       Operation = 4
	Operation_OPERATION_FILE_STAT        Operation = 5
	Operation_OPERATION_FILE_LIST        Operation = 6
	Operation_OPERATION_FILE_MKDIR       Operation = 7
	Operation_OPERATION_FILE_REMOVE      Operation = 8
	Operation_OPERATION_PTY              Operation = 9
	Operation_OPERATION_TCP              Operation = 10
	Operation_OPERATION_SHUTDOWN         Operation = 11
	Operation_OPERATION_FORMAT_WORKSPACE Operation = 12
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0:  "OPERATION_UNSPECIFIED",
		1:  "OPERATION_START",
		2:  "OPERATION_EXEC",
		3:  "OPERATION_FILE_READ",
		4:  "OPERATION_FILE_WRITE",
		5:  "OPERATION_FILE_STAT",
		6:  "OPERATION_FILE_LIST",
		7:  "OPERATION_FILE_MKDIR",
		8:  "OPERATION_FILE_REMOVE",
		9:  "OPERATION_PTY",
		10: "OPERATION_TCP",
		11: "OPERATION_SHUTDOWN",
		12: "OPERATION_FORMAT_WORKSPACE",
	}
	Operation_value = map[string]int32{
		"OPERATION_UNSPECIFIED":      0,
		"OPERATION_START":            1,
		"OPERATION_EXEC":             2,
		"OPERATION_FILE_READ":        3,
		"OPERATION_FILE_WRITE":       4,
		"OPERATION_FILE_STAT":        5,
		"OPERATION_FILE_LIST":        6,
		"OPERATION_FILE_MKDIR":       7,
		"OPERATION_FILE_REMOVE":      8,
		"OPERATION_PTY":              9,
		"OPERATION_TCP":              10,
		"OPERATION_SHUTDOWN":         11,
		"OPERATION_FORMAT_WORKSPACE": 12,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_microsandbox_helper_v1_helper_proto_enumTypes[0].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_microsandbox_helper_v1_helper_proto_enumTypes[0]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_microsandbox_helper_v1_helper_proto_rawDescGZIP(), []int{0}
}

type HelperNetworkPolicyMode int32

const (
	HelperNetworkPolicyMode_HELPER_NETWORK_POLICY_MODE_UNSPECIFIED HelperNetworkPolicyMode = 0
	HelperNetworkPolicyMode_HELPER_NETWORK_POLICY_MODE_DENY_ALL    HelperNetworkPolicyMode = 1
	HelperNetworkPolicyMode_HELPER_NETWORK_POLICY_MODE_ALLOW_LIST  HelperNetworkPolicyMode = 2
)

// Enum value maps for HelperNetworkPolicyMode.
var (
	HelperNetworkPolicyMode_name = map[int32]string{
		0: "HELPER_NETWORK_POLICY_MODE_UNSPECIFIED",
		1: "HELPER_NETWORK_POLICY_MODE_DENY_ALL",
		2: "HELPER_NETWORK_POLICY_MODE_ALLOW_LIST",
	}
	HelperNetworkPolicyMode_value = map[string]int32{
		"HELPER_NETWORK_POLICY_MODE_UNSPECIFIED": 0,
		"HELPER_NETWORK_POLICY_MODE_DENY_ALL":    1,
		"HELPER_NETWORK_POLICY_MODE_ALLOW_LIST":  2,
	}
)

func (x HelperNetworkPolicyMode) Enum() *HelperNetworkPolicyMode {
	p := new(HelperNetworkPolicyMode)
	*p = x
	return p
}

func (x HelperNetworkPolicyMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HelperNetworkPolicyMode) Descriptor() protoreflect.EnumDescriptor {
	return file_microsandbox_helper_v1_helper_proto_enumTypes[1].Descriptor()
}

func (HelperNetworkPolicyMode) Type() protoreflect.EnumType {
	return &file_microsandbox_helper_v1_helper_proto_enumTypes[1]
}

func (x HelperNetworkPolicyMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HelperNetworkPolicyMode.Descriptor instead.
func (HelperNetworkPolicyMode) EnumDescriptor() ([]byte, []int) {
	return file_microsandbox_helper_v1_helper_proto_rawDescGZIP(), []int{1}
}

type HelperNetworkProtocol int32

const (
	HelperNetworkProtocol_HELPER_NETWORK_PROTOCOL_UNSPECIFIED HelperNetworkProtocol = 0
	HelperNetworkProtocol_HELPER_NETWORK_PROTOCOL_TCP         HelperNetworkProtocol = 1
	HelperNetworkProtocol_HELPER_NETWORK_PROTOCOL_HTTP        HelperNetworkProtocol = 2
	HelperNetworkProtocol_HELPER_NETWORK_PROTOCOL_HTTPS       HelperNetworkProtocol = 3
)

// Enum value maps for HelperNetworkProtocol.
var (
	HelperNetworkProtocol_name = map[int32]string{
		0: "HELPER_NETWORK_PROTOCOL_UNSPECIFIED",
		1: "HELPER_NETWORK_PROTOCOL_TCP",
		2: "HELPER_NETWORK_PROTOCOL_HTTP",
		3: "HELPER_NETWORK_PROTOCOL_HTTPS",
	}
	HelperNetworkProtocol_value = map[string]int32{
		"HELPER_NETWORK_PROTOCOL_UNSPECIFIED": 0,
		"HELPER_NETWORK_PROTOCOL_TCP":         1,
		"HELPER_NETWORK_PROTOCOL_HTTP":        2,
		"HELPER_NETWORK_PROTOCOL_HTTPS":       3,
	}
)

func (x HelperNetworkProtocol) Enum() *HelperNetworkProtocol {
	p := new(HelperNetworkProtocol)
	*p = x
	return p
}

func (x HelperNetworkProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HelperNetworkProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_microsandbox_helper_v1_helper_proto_enumTypes[2].Descriptor()
}

func (HelperNetworkProtocol) Type() protoreflect.EnumType {
	return &file_microsandbox_helper_v1_helper_proto_enumTypes[2]
}

func (x HelperNetworkProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HelperNetworkProtocol.Descriptor instead.
func (HelperNetworkProtocol) EnumDescriptor() ([]byte, []int) {
	return file_microsandbox_helper_v1_helper_proto_rawDescGZIP(), []int{2}
}

type Envelope struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	RequestId       uint64                 `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	StreamId        uint64                 `protobuf:"varint,3,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Sequence        uint64                 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Types that are valid to be assigned to Message:
	//
	//	*Envelope_Start
	//	*Envelope_Ready
	//	*Envelope_Exec
	//	*Envelope_File
	//	*Envelope_Pty
	//	*Envelope_Tcp
	//	*Envelope_Shutdown
	//	*Envelope_Cancel
	//	*Envelope_StreamData
	//	*Envelope_StreamCredit
	//	*Envelope_Terminal
	//	*Envelope_Diagnostic
	//	*Envelope_FormatWorkspace
	Message       isEnvelope_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_microsandbox_helper_v1_helper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_microsandbox_helper_v1_helper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_microsandbox_helper_v1_helper_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Envelope) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *Envelope) GetStreamId() uint64 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *Envelope) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Envelope) GetMessage() isEnvelope_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Envelope) GetStart() *StartRequest {
	if x != nil {
		if x, ok := x.Message.(*Envelope_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *Envelope) GetReady() *ReadyEvent {
	if x != nil {
		if x, ok := x.Message.(*Envelope_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

func (x *Envelope) GetExec() *ExecRequest {
	if x != nil {
		if x, ok := x.Message.(*Envelope_Exec); ok {
			return x.Exec
		}
	}
	return nil
}

func (x *Envelope) GetFile() *FileRequest {
	if x != nil {
		if x, ok := x.Message.(*Envelope_File); ok {
			return x.File
		}
	}
	return nil
}

func (x *Envelope) GetPty() *PtyRequest {
	if x != nil {
		if x, ok := x.Message.(*Envelope_Pty); ok {
			return x.Pty
		}
	}
	return nil
}

func (x *Envelope) GetTcp() *TcpRequest {
	if x != nil {
		if x, ok := x.Message.(*Envelope_Tcp); ok {
			return x.Tcp
		}
	}
	return nil
}

func (x *Envelope) GetShutdown() *ShutdownRequest {
	if x != nil {
		if x, ok := x.Message.(*Envelope_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

func (x *Envelope) GetCancel() *CancelRequest {
	if x != nil {
		if x, ok := x.Message.(*Envelope_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *Envelope) GetStreamData() *StreamData {
	if x != nil {
		if x, ok := x.Message.(*Envelope_StreamData); ok {
			return x.StreamData
		}
	}
	return nil
}

func (x *Envelope) GetStreamCredit() *StreamCredit {
	if x != nil {
		if x, ok := x.Message.(*Envelope_StreamCredit); ok {
			return x.StreamCredit
		}
	}
	return nil
}

func (x *Envelope) GetTerminal() *TerminalEvent {
	if x != nil {
		if x, ok := x.Message.(*Envelope_Terminal); ok {
			return x.Terminal
		}
	}
	return nil
}

func (x *Envelope) GetDiagnostic() *DiagnosticEvent {
	if x != nil {
		if x, ok := x.Message.(*Envelope_Diagnostic); ok {
			return x.Diagnostic
		}
	}
	return nil
}

func (x *Envelope) GetFormatWorkspace() *FormatWorkspaceRequest {
	if x != nil {
		if x, ok := x.Message.(*Envelope_FormatWorkspace); ok {
			return x.FormatWorkspace
		}
	}
	return nil
}

type isEnvelope_Message interface {
	isEnvelope_Message()
}

type Envelope_Start struct {
	Start *StartRequest `protobuf:"bytes,10,opt,name=start,proto3,oneof"`
}

type Envelope_Ready struct {
	Ready *ReadyEvent `protobuf:"bytes,11,opt,name=ready,proto3,oneof"`
}

type Envelope_Exec struct {
	Exec *ExecRequest `protobuf:"bytes,12,opt,name=exec,proto3,oneof"`
}

type Envelope_File struct {
	File *FileRequest `protobuf:"bytes,13,opt,name=file,proto3,oneof"`
}

type Envelope_Pty struct {
	Pty *PtyRequest `protobuf:"bytes,14,opt,name=pty,proto3,oneof"`
}

type Envelope_Tcp struct {
	Tcp *TcpRequest `protobuf:"bytes,15,opt,name=tcp,proto3,oneof"`
}

type Envelope_Shutdown struct {
	Shutdown *ShutdownRequest `protobuf:"bytes,16,opt,name=shutdown,proto3,oneof"`
}

type Envelope_Cancel struct {
	Cancel *CancelRequest `protobuf:"bytes,17,opt,name=cancel,proto3,oneof"`
}

type Envelope_StreamData struct {
	StreamData *StreamData `protobuf:"bytes,18,opt,name=stream_data,json=streamData,proto3,oneof"`
}

type Envelope_StreamCredit struct {
	StreamCredit *StreamCredit `protobuf:"bytes,19,opt,name=stream_credit,json=streamCredit,proto3,oneof"`
}

type Envelope_Terminal struct {
	Terminal *TerminalEvent `protobuf:"bytes,20,opt,name=terminal,proto3,oneof"`
}

type Envelope_Diagnostic struct {
	Diagnostic *DiagnosticEvent `protobuf:"bytes,21,opt,name=diagnostic,proto3,oneof"`
}

type Envelope_FormatWorkspace struct {
	FormatWorkspace *FormatWorkspaceRequest `protobuf:"bytes,22,opt,name=format_workspace,json=formatWorkspace,proto3,oneof"`
}

func (*Envelope_Start) isEnvelope_Message() {}

func (*Envelope_Ready) isEnvelope_Message() {}

func (*Envelope_Exec) isEnvelope_Message() {}

func (*Envelope_File) isEnvelope_Message() {}

func (*Envelope_Pty) isEnvelope_Message() {}

func (*Envelope_Tcp) isEnvelope_Message() {}

func (*Envelope_Shutdown) isEnvelope_Message() {}

func (*Envelope_Cancel) isEnvelope_Message() {}

func (*Envelope_StreamData) isEnvelope_Message() {}

func (*Envelope_StreamCredit) isEnvelope_Message() {}

func (*Envelope_Terminal) isEnvelope_Message() {}

func (*Envelope_Diagnostic) isEnvelope_Message() {}

func (*Envelope_FormatWorkspace) isEnvelope_Message() {}

type StartRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	MaterializationDigest  string                 `protobuf:"bytes,1,opt,name=materialization_digest,json=materializationDigest,proto3" json:"materialization_digest,omitempty"`
	GuestArchitecture      string                 `protobuf:"bytes,2,opt,name=guest_architecture,json=guestArchitecture,proto3" json:"guest_architecture,omitempty"`
	VcpuCount              uint32                 `protobuf:"varint,3,opt,name=vcpu_count,json=vcpuCount,proto3" json:"vcpu_count,omitempty"`
	MemoryBytes            uint64                 `protobuf:"varint,4,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	FlatRootDigest         string                 `protobuf:"bytes,5,opt,name=flat_root_digest,json=flatRootDigest,proto3" json:"flat_root_digest,omitempty"`
	Environment            []string               `protobuf:"bytes,6,rep,name=environment,proto3" json:"environment,omitempty"`
	NetworkPolicy          *HelperNetworkPolicy   `protobuf:"bytes,7,opt,name=network_policy,json=networkPolicy,proto3" json:"network_policy,omitempty"`
	StableWorkspaceBlockId string                 `protobuf:"bytes,8,opt,name=stable_workspace_block_id,json=stableWorkspaceBlockId,proto3" json:"stable_workspace_block_id,omitempty"`
	WorkspaceCapacityBytes uint64                 `protobuf:"varint,9,opt,name=workspace_capacity_bytes,json=workspaceCapacityBytes,proto3" json:"workspace_capacity_bytes,omitempty"`
	WorkspaceUuid          []byte                 `protobuf:"bytes,10,opt,name=workspace_uuid,json=workspaceUuid,proto3" json:"workspace_uuid,omitempty"`
	FlatRootPath           string                 `protobuf:"bytes,11,opt,name=flat_root_path,json=flatRootPath,proto3" json:"flat_root_path,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_microsandbox_helper_v1_helper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_microsandbox_helper_v1_helper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_microsandbox_helper_v1_helper_proto_rawDescGZIP(), []int{1}
}

func (x *StartRequest) GetMaterializationDigest() string {
	if x != nil {
		return x.MaterializationDigest
	}
	return ""
}

func (x *StartRequest) GetGuestArchitecture() string {
	if x != nil {
		return x.GuestArchitecture
	}
	return ""
}

func (x *StartRequest) GetVcpuCount() uint32 {
	if x != nil {
		return x.VcpuCount
	}
	return 0
}

func (x *StartRequest) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *StartRequest) GetFlatRootDigest() string {
	if x != nil {
		return x.FlatRootDigest
	}
	return ""
}

func (x *StartRequest) GetEnvironment() []string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *StartRequest) GetNetworkPolicy() *HelperNetworkPolicy {
	if x != nil {
		return x.NetworkPolicy
	}
	return nil
}

func (x *StartRequest) GetStableWorkspaceBlockId() string {
	if x != nil {
		return x.StableWorkspaceBlockId
	}
	return ""
}

func (x *StartRequest) GetWorkspaceCapacityBytes() uint64 {
	if x != nil {
		return x.WorkspaceCapacityBytes
	}
	return 0
}

func (x *StartRequest) GetWorkspaceUuid() []byte {
	if x != nil {
		return x.WorkspaceUuid
	}
	return nil
}

func (x *StartRequest) GetFlatRootPath() string {
	if x != nil {
		return x.FlatRootPath
	}
	return ""
}

type HelperNetworkDestination struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Target:
	//
	//	*HelperNetworkDestination_Domain
	//	*HelperNetworkDestination_Cidr
	Target        isHelperNetworkDestination_Target `protobuf_oneof:"target"`
	Protocol      HelperNetworkProtocol             `protobuf:"varint,3,opt,name=protocol,proto3,enum=secondbox.microsandbox.helper.v1.HelperNetworkProtocol" json:"protocol,omitempty"`
	Port          uint32                            `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelperNetworkDestination) Reset() {
	*x = HelperNetworkDestination{}
	mi := &file_microsandbox_helper_v1_helper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelperNetworkDestination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelperNetworkDestination) ProtoMessage() {}

func (x *HelperNetworkDestination) ProtoReflect() protoreflect.Message {
	mi := &file_microsandbox_helper_v1_helper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelperNetworkDestination.ProtoReflect.Descriptor instead.
func (*HelperNetworkDestination) Descriptor() ([]byte, []int) {
	return file_microsandbox_helper_v1_helper_proto_rawDescGZIP(), []int{2}
}

func (x *HelperNetworkDestination) GetTarget() isHelperNetworkDestination_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *HelperNetworkDestination) GetDomain() string {
	if x != nil {
		if x, ok := x.Target.(*HelperNetworkDestination_Domain); ok {
			return x.Domain
		}
	}
	return ""
}

func (x *HelperNetworkDestination) GetCidr() string {
	if x != nil {
		if x, ok := x.Target.(*HelperNetworkDestination_Cidr); ok {
			return x.Cidr
		}
	}
	return ""
}

func (x *HelperNetworkDestination) GetProtocol() HelperNetworkProtocol {
	if x != nil {
		return x.Protocol
	}
	return HelperNetworkProtocol_HELPER_NETWORK_PROTOCOL_UNSPECIFIED
}

func (x *HelperNetworkDestination) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type isHelperNetworkDestination_Target interface {
	isHelperNetworkDestination_Target()
}

type HelperNetworkDestination_Domain struct {
	Domain string `protobuf:"bytes,1,opt,name=domain,proto3,oneof"`
}

type HelperNetworkDestination_Cidr struct {
	Cidr string `protobuf:"bytes,2,opt,name=cidr,proto3,oneof"`
}

func (*HelperNetworkDestination_Domain) isHelperNetworkDestination_Target() {}

func (*HelperNetworkDestination_Cidr) isHelperNetworkDestination_Target() {}

type HelperNetworkPolicy struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Mode          HelperNetworkPolicyMode     `protobuf:"varint,1,opt,name=mode,proto3,enum=secondbox.microsandbox.helper.v1.HelperNetworkPolicyMode" json:"mode,omitempty"`
	Destinations  []*HelperNetworkDestination `protobuf:"bytes,2,rep,name=destinations,proto3" json:"destinations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelperNetworkPolicy) Reset() {
	*x = HelperNetworkPolicy{}
	mi := &file_microsandbox_helper_v1_helper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelperNetworkPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelperNetworkPolicy) ProtoMessage() {}

func (x *HelperNetworkPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_microsandbox_helper_v1_helper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelperNetworkPolicy.ProtoReflect.Descriptor instead.
func (*HelperNetworkPolicy) Descriptor() ([]byte, []int) {
	return file_microsandbox_helper_v1_helper_proto_rawDescGZIP(), []int{3}
}

func (x *HelperNetworkPolicy) GetMode() HelperNetworkPolicyMode {
	if x != nil {
		return x.Mode
	}
	return HelperNetworkPolicyMode_HELPER_NETWORK_POLICY_MODE_UNSPECIFIED
}

func (x *HelperNetworkPolicy) GetDestinations() []*HelperNetworkDestination {
	if x != nil {
		return x.Destinations
	}
	return nil
}

type ReadyEvent struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	HelperVersion           string                 `protobuf:"bytes,1,opt,name=helper_version,json=helperVersion,proto3" json:"helper_version,omitempty"`
	DependencyVersion       string                 `protobuf:"bytes,2,opt,name=dependency_version,json=dependencyVersion,proto3" json:"dependency_version,omitempty"`
	HostPlatform            string                 `protobuf:"bytes,3,opt,name=host_platform,json=hostPlatform,proto3" json:"host_platform,omitempty"`
	AgentProtocolGeneration uint32                 `protobuf:"varint,4,opt,name=agent_protocol_generation,json=agentProtocolGeneration,proto3" json:"agent_protocol_generation,omitempty"`
	AgentFeatures           []string               `protobuf:"bytes,5,rep,name=agent_features,json=agentFeatures,proto3" json:"agent_features,omitempty"`
	Operations              []Operation            `protobuf:"varint,6,rep,packed,name=operations,proto3,enum=secondbox.microsandbox.helper.v1.Operation" json:"operations,omitempty"`
	MaterializationDigest   string                 `protobuf:"bytes,7,opt,name=materialization_digest,json=materializationDigest,proto3" json:"materialization_digest,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ReadyEvent) Reset() {
	*x = ReadyEvent{}
	mi := &file_microsandbox_helper_v1_helper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyEvent) ProtoMessage() {}

func (x *ReadyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_microsandbox_helper_v1_helper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyEvent.ProtoReflect.Descriptor instead.
func (*ReadyEvent) Descriptor() ([]byte, []int) {
	return file_microsandbox_helper_v1_helper_proto_rawDescGZIP(), []int{4}
}

func (x *ReadyEvent) GetHelperVersion() string {
	if x != nil {
		return x.HelperVersion
	}
	return ""
}

func (x *ReadyEvent) GetDependencyVersion() string {
	if x != nil {
		return x.DependencyVersion
	}
	return ""
}

func (x *ReadyEvent) GetHostPlatform() string {
	if x != nil {
		return x.HostPlatform
	}
	return ""
}

func (x *ReadyEvent) GetAgentProtocolGeneration() uint32 {
	if x != nil {
		return x.AgentProtocolGeneration
	}
	return 0
}

func (x *ReadyEvent) GetAgentFeatures() []string {
	if x != nil {
		return x.AgentFeatures
	}
	return nil
}

func (x *ReadyEvent) GetOperations() []Operation {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *ReadyEvent) GetMaterializationDigest() string {
	if x != nil {
		return x.MaterializationDigest
	}
	return ""
}

type ExecRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Argv             []string               `protobuf:"bytes,1,rep,name=argv,proto3" json:"argv,omitempty"`
	WorkingDirectory string                 `protobuf:"bytes,2,opt,name=working_directory,json=workingDirectory,proto3" json:"working_directory,omitempty"`
	Environment      []string               `protobuf:"bytes,3,rep,name=environment,proto3" json:"environment,omitempty"`
	DeadlineUnixMs   uint64                 `protobuf:"varint,4,opt,name=deadline_unix_ms,json=deadlineUnixMs,proto3" json:"deadline_unix_ms,omitempty"`
	Pty              bool                   `protobuf:"varint,5,opt,name=pty,proto3" json:"pty,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_microsandbox_helper_v1_helper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_microsandbox_helper_v1_helper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_microsandbox_helper_v1_helper_proto_rawDescGZIP(), []int{5}
}

func (x *ExecRequest) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *ExecRequest) GetWorkingDirectory() string {
	if x != nil {
		return x.WorkingDirectory
	}
	return ""
}

func (x *ExecRequest) GetEnvironment() []string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *ExecRequest) GetDeadlineUnixMs() uint64 {
	if x != nil {
		return x.DeadlineUnixMs
	}
	return 0
}

func (x *ExecRequest) GetPty() bool {
	if x != nil {
		return x.Pty
	}
	return false
}

type FileRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Operation       Operation              `protobuf:"varint,1,opt,name=operation,proto3,enum=secondbox.microsandbox.helper.v1.Operation" json:"operation,omitempty"`
	Path            string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	DestinationPath string                 `protobuf:"bytes,3,opt,name=destination_path,json=destinationPath,proto3" json:"destination_path,omitempty"`
	Offset          uint64                 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit           uint64                 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Mode            uint32                 `protobuf:"varint,6,opt,name=mode,proto3" json:"mode,omitempty"`
	Recursive       bool                   `protobuf:"varint,7,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	mi := &file_microsandbox_helper_v1_helper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_microsandbox_helper_v1_helper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_microsandbox_helper_v1_helper_proto_rawDescGZIP(), []int{6}
}

func (x *FileRequest) GetOperation() Operation {
	if x != nil {
		return x.Operation
	}
	return Operation_OPERATION_UNSPECIFIED
}

func (x *FileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileRequest) GetDestinationPath() string {
	if x != nil {
		return x.DestinationPath
	}
	return ""
}

func (x *FileRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FileRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FileRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FileRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

type PtyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          uint32                 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Columns       uint32                 `protobuf:"varint,2,opt,name=columns,proto3" json:"columns,omitempty"`
	Terminal      string                 `protobuf:"bytes,3,opt,name=terminal,proto3" json:"terminal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PtyRequest) Reset() {
	*x = PtyRequest{}
	mi := &file_microsandbox_helper_v1_helper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PtyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtyRequest) ProtoMessage() {}

func (x *PtyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_microsandbox_helper_v1_helper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtyRequest.ProtoReflect.Descriptor instead.
func (*PtyRequest) Descriptor() ([]byte, []int) {
	return file_microsandbox_helper_v1_helper_proto_rawDescGZIP(), []int{7}
}

func (x *PtyRequest) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *PtyRequest) GetColumns() uint32 {
	if x != nil {
		return x.Columns
	}
	return 0
}

func (x *PtyRequest) GetTerminal() string {
	if x != nil {
		return x.Terminal
	}
	return ""
}

type TcpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TcpRequest) Reset() {
	*x = TcpRequest{}
	mi := &file_microsandbox_helper_v1_helper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TcpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcpRequest) ProtoMessage() {}

func (x *TcpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_microsandbox_helper_v1_helper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcpRequest.ProtoReflect.Descriptor instead.
func (*TcpRequest) Descriptor() ([]byte, []int) {
	return file_microsandbox_helper_v1_helper_proto_rawDescGZIP(), []int{8}
}

func (x *TcpRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *TcpRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type ShutdownRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	FlushDeadlineUnixMs uint64                 `protobuf:"varint,1,opt,name=flush_deadline_unix_ms,json=flushDeadlineUnixMs,proto3" json:"flush_deadline_unix_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_microsandbox_helper_v1_helper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_microsandbox_helper_v1_helper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_microsandbox_helper_v1_helper_proto_rawDescGZIP(), []int{9}
}

func (x *ShutdownRequest) GetFlushDeadlineUnixMs() uint64 {
	if x != nil {
		return x.FlushDeadlineUnixMs
	}
	return 0
}

type CancelRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TargetRequestId uint64                 `protobuf:"varint,1,opt,name=target_request_id,json=targetRequestId,proto3" json:"target_request_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_microsandbox_helper_v1_helper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_microsandbox_helper_v1_helper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_microsandbox_helper_v1_helper_proto_rawDescGZIP(), []int{10}
}

func (x *CancelRequest) GetTargetRequestId() uint64 {
	if x != nil {
		return x.TargetRequestId
	}
	return 0
}

type StreamData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Eof           bool                   `protobuf:"varint,2,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamData) Reset() {
	*x = StreamData{}
	mi := &file_microsandbox_helper_v1_helper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamData) ProtoMessage() {}

func (x *StreamData) ProtoReflect() protoreflect.Message {
	mi := &file_microsandbox_helper_v1_helper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamData.ProtoReflect.Descriptor instead.
func (*StreamData) Descriptor() ([]byte, []int) {
	return file_microsandbox_helper_v1_helper_proto_rawDescGZIP(), []int{11}
}

func (x *StreamData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StreamData) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

type StreamCredit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bytes         uint64                 `protobuf:"varint,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamCredit) Reset() {
	*x = StreamCredit{}
	mi := &file_microsandbox_helper_v1_helper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamCredit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamCredit) ProtoMessage() {}

func (x *StreamCredit) ProtoReflect() protoreflect.Message {
	mi := &file_microsandbox_helper_v1_helper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamCredit.ProtoReflect.Descriptor instead.
func (*StreamCredit) Descriptor() ([]byte, []int) {
	return file_microsandbox_helper_v1_helper_proto_rawDescGZIP(), []int{12}
}

func (x *StreamCredit) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

type TerminalEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalEvent) Reset() {
	*x = TerminalEvent{}
	mi := &file_microsandbox_helper_v1_helper_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalEvent) ProtoMessage() {}

func (x *TerminalEvent) ProtoReflect() protoreflect.Message {
	mi := &file_microsandbox_helper_v1_helper_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalEvent.ProtoReflect.Descriptor instead.
func (*TerminalEvent) Descriptor() ([]byte, []int) {
	return file_microsandbox_helper_v1_helper_proto_rawDescGZIP(), []int{13}
}

func (x *TerminalEvent) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TerminalEvent) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *TerminalEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DiagnosticEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiagnosticEvent) Reset() {
	*x = DiagnosticEvent{}
	mi := &file_microsandbox_helper_v1_helper_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnosticEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosticEvent) ProtoMessage() {}

func (x *DiagnosticEvent) ProtoReflect() protoreflect.Message {
	mi := &file_microsandbox_helper_v1_helper_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosticEvent.ProtoReflect.Descriptor instead.
func (*DiagnosticEvent) Descriptor() ([]byte, []int) {
	return file_microsandbox_helper_v1_helper_proto_rawDescGZIP(), []int{14}
}

func (x *DiagnosticEvent) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DiagnosticEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type FormatWorkspaceRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	LogicalCapacityBytes uint64                 `protobuf:"varint,1,opt,name=logical_capacity_bytes,json=logicalCapacityBytes,proto3" json:"logical_capacity_bytes,omitempty"`
	Label                string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	WorkspaceUuid        []byte                 `protobuf:"bytes,3,opt,name=workspace_uuid,json=workspaceUuid,proto3" json:"workspace_uuid,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *FormatWorkspaceRequest) Reset() {
	*x = FormatWorkspaceRequest{}
	mi := &file_microsandbox_helper_v1_helper_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormatWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormatWorkspaceRequest) ProtoMessage() {}

func (x *FormatWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_microsandbox_helper_v1_helper_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormatWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*FormatWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_microsandbox_helper_v1_helper_proto_rawDescGZIP(), []int{15}
}

func (x *FormatWorkspaceRequest) GetLogicalCapacityBytes() uint64 {
	if x != nil {
		return x.LogicalCapacityBytes
	}
	return 0
}

func (x *FormatWorkspaceRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *FormatWorkspaceRequest) GetWorkspaceUuid() []byte {
	if x != nil {
		return x.WorkspaceUuid
	}
	return nil
}

var File_microsandbox_helper_v1_helper_proto protoreflect.FileDescriptor

const file_microsandbox_helper_v1_helper_proto_rawDesc = "" +
	"\n" +
	"#microsandbox-helper/v1/helper.proto\x12 secondbox.microsandbox.helper.v1\"\x83\t\n" +
	"\bEnvelope\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\x04R\trequestId\x12\x1b\n" +
	"\tstream_id\x18\x03 \x01(\x04R\bstreamId\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x04R\bsequence\x12F\n" +
	"\x05start\x18\n" +
	" \x01(\v2..secondbox.microsandbox.helper.v1.StartRequestH\x00R\x05start\x12D\n" +
	"\x05ready\x18\v \x01(\v2,.secondbox.microsandbox.helper.v1.ReadyEventH\x00R\x05ready\x12C\n" +
	"\x04exec\x18\f \x01(\v2-.secondbox.microsandbox.helper.v1.ExecRequestH\x00R\x04exec\x12C\n" +
	"\x04file\x18\r \x01(\v2-.secondbox.microsandbox.helper.v1.FileRequestH\x00R\x04file\x12@\n" +
	"\x03pty\x18\x0e \x01(\v2,.secondbox.microsandbox.helper.v1.PtyRequestH\x00R\x03pty\x12@\n" +
	"\x03tcp\x18\x0f \x01(\v2,.secondbox.microsandbox.helper.v1.TcpRequestH\x00R\x03tcp\x12O\n" +
	"\bshutdown\x18\x10 \x01(\v21.secondbox.microsandbox.helper.v1.ShutdownRequestH\x00R\bshutdown\x12I\n" +
	"\x06cancel\x18\x11 \x01(\v2/.secondbox.microsandbox.helper.v1.CancelRequestH\x00R\x06cancel\x12O\n" +
	"\vstream_data\x18\x12 \x01(\v2,.secondbox.microsandbox.helper.v1.StreamDataH\x00R\n" +
	"streamData\x12U\n" +
	"\rstream_credit\x18\x13 \x01(\v2..secondbox.microsandbox.helper.v1.StreamCreditH\x00R\fstreamCredit\x12M\n" +
	"\bterminal\x18\x14 \x01(\v2/.secondbox.microsandbox.helper.v1.TerminalEventH\x00R\bterminal\x12S\n" +
	"\n" +
	"diagnostic\x18\x15 \x01(\v21.secondbox.microsandbox.helper.v1.DiagnosticEventH\x00R\n" +
	"diagnostic\x12e\n" +
	"\x10format_workspace\x18\x16 \x01(\v28.secondbox.microsandbox.helper.v1.FormatWorkspaceRequestH\x00R\x0fformatWorkspaceB\t\n" +
	"\amessage\"\xa2\x04\n" +
	"\fStartRequest\x125\n" +
	"\x16materialization_digest\x18\x01 \x01(\tR\x15materializationDigest\x12-\n" +
	"\x12guest_architecture\x18\x02 \x01(\tR\x11guestArchitecture\x12\x1d\n" +
	"\n" +
	"vcpu_count\x18\x03 \x01(\rR\tvcpuCount\x12!\n" +
	"\fmemory_bytes\x18\x04 \x01(\x04R\vmemoryBytes\x12(\n" +
	"\x10flat_root_digest\x18\x05 \x01(\tR\x0eflatRootDigest\x12 \n" +
	"\venvironment\x18\x06 \x03(\tR\venvironment\x12\\\n" +
	"\x0enetwork_policy\x18\a \x01(\v25.secondbox.microsandbox.helper.v1.HelperNetworkPolicyR\rnetworkPolicy\x129\n" +
	"\x19stable_workspace_block_id\x18\b \x01(\tR\x16stableWorkspaceBlockId\x128\n" +
	"\x18workspace_capacity_bytes\x18\t \x01(\x04R\x16workspaceCapacityBytes\x12%\n" +
	"\x0eworkspace_uuid\x18\n" +
	" \x01(\fR\rworkspaceUuid\x12$\n" +
	"\x0eflat_root_path\x18\v \x01(\tR\fflatRootPath\"\xbd\x01\n" +
	"\x18HelperNetworkDestination\x12\x18\n" +
	"\x06domain\x18\x01 \x01(\tH\x00R\x06domain\x12\x14\n" +
	"\x04cidr\x18\x02 \x01(\tH\x00R\x04cidr\x12S\n" +
	"\bprotocol\x18\x03 \x01(\x0e27.secondbox.microsandbox.helper.v1.HelperNetworkProtocolR\bprotocol\x12\x12\n" +
	"\x04port\x18\x04 \x01(\rR\x04portB\b\n" +
	"\x06target\"\xc4\x01\n" +
	"\x13HelperNetworkPolicy\x12M\n" +
	"\x04mode\x18\x01 \x01(\x0e29.secondbox.microsandbox.helper.v1.HelperNetworkPolicyModeR\x04mode\x12^\n" +
	"\fdestinations\x18\x02 \x03(\v2:.secondbox.microsandbox.helper.v1.HelperNetworkDestinationR\fdestinations\"\xee\x02\n" +
	"\n" +
	"ReadyEvent\x12%\n" +
	"\x0ehelper_version\x18\x01 \x01(\tR\rhelperVersion\x12-\n" +
	"\x12dependency_version\x18\x02 \x01(\tR\x11dependencyVersion\x12#\n" +
	"\rhost_platform\x18\x03 \x01(\tR\fhostPlatform\x12:\n" +
	"\x19agent_protocol_generation\x18\x04 \x01(\rR\x17agentProtocolGeneration\x12%\n" +
	"\x0eagent_features\x18\x05 \x03(\tR\ragentFeatures\x12K\n" +
	"\n" +
	"operations\x18\x06 \x03(\x0e2+.secondbox.microsandbox.helper.v1.OperationR\n" +
	"operations\x125\n" +
	"\x16materialization_digest\x18\a \x01(\tR\x15materializationDigest\"\xac\x01\n" +
	"\vExecRequest\x12\x12\n" +
	"\x04argv\x18\x01 \x03(\tR\x04argv\x12+\n" +
	"\x11working_directory\x18\x02 \x01(\tR\x10workingDirectory\x12 \n" +
	"\venvironment\x18\x03 \x03(\tR\venvironment\x12(\n" +
	"\x10deadline_unix_ms\x18\x04 \x01(\x04R\x0edeadlineUnixMs\x12\x10\n" +
	"\x03pty\x18\x05 \x01(\bR\x03pty\"\xf7\x01\n" +
	"\vFileRequest\x12I\n" +
	"\toperation\x18\x01 \x01(\x0e2+.secondbox.microsandbox.helper.v1.OperationR\toperation\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12)\n" +
	"\x10destination_path\x18\x03 \x01(\tR\x0fdestinationPath\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x04R\x06offset\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x04R\x05limit\x12\x12\n" +
	"\x04mode\x18\x06 \x01(\rR\x04mode\x12\x1c\n" +
	"\trecursive\x18\a \x01(\bR\trecursive\"V\n" +
	"\n" +
	"PtyRequest\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\rR\x04rows\x12\x18\n" +
	"\acolumns\x18\x02 \x01(\rR\acolumns\x12\x1a\n" +
	"\bterminal\x18\x03 \x01(\tR\bterminal\"4\n" +
	"\n" +
	"TcpRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\"F\n" +
	"\x0fShutdownRequest\x123\n" +
	"\x16flush_deadline_unix_ms\x18\x01 \x01(\x04R\x13flushDeadlineUnixMs\";\n" +
	"\rCancelRequest\x12*\n" +
	"\x11target_request_id\x18\x01 \x01(\x04R\x0ftargetRequestId\"2\n" +
	"\n" +
	"StreamData\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x10\n" +
	"\x03eof\x18\x02 \x01(\bR\x03eof\"$\n" +
	"\fStreamCredit\x12\x14\n" +
	"\x05bytes\x18\x01 \x01(\x04R\x05bytes\"^\n" +
	"\rTerminalEvent\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"9\n" +
	"\x0fDiagnosticEvent\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\x8b\x01\n" +
	"\x16FormatWorkspaceRequest\x124\n" +
	"\x16logical_capacity_bytes\x18\x01 \x01(\x04R\x14logicalCapacityBytes\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12%\n" +
	"\x0eworkspace_uuid\x18\x03 \x01(\fR\rworkspaceUuid*\xc7\x02\n" +
	"\tOperation\x12\x19\n" +
	"\x15OPERATION_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fOPERATION_START\x10\x01\x12\x12\n" +
	"\x0eOPERATION_EXEC\x10\x02\x12\x17\n" +
	"\x13OPERATION_FILE_READ\x10\x03\x12\x18\n" +
	"\x14OPERATION_FILE_WRITE\x10\x04\x12\x17\n" +
	"\x13OPERATION_FILE_STAT\x10\x05\x12\x17\n" +
	"\x13OPERATION_FILE_LIST\x10\x06\x12\x18\n" +
	"\x14OPERATION_FILE_MKDIR\x10\a\x12\x19\n" +
	"\x15OPERATION_FILE_REMOVE\x10\b\x12\x11\n" +
	"\rOPERATION_PTY\x10\t\x12\x11\n" +
	"\rOPERATION_TCP\x10\n" +
	"\x12\x16\n" +
	"\x12OPERATION_SHUTDOWN\x10\v\x12\x1e\n" +
	"\x1aOPERATION_FORMAT_WORKSPACE\x10\f*\x99\x01\n" +
	"\x17HelperNetworkPolicyMode\x12*\n" +
	"&HELPER_NETWORK_POLICY_MODE_UNSPECIFIED\x10\x00\x12'\n" +
	"#HELPER_NETWORK_POLICY_MODE_DENY_ALL\x10\x01\x12)\n" +
	"%HELPER_NETWORK_POLICY_MODE_ALLOW_LIST\x10\x02*\xa6\x01\n" +
	"\x15HelperNetworkProtocol\x12'\n" +
	"#HELPER_NETWORK_PROTOCOL_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bHELPER_NETWORK_PROTOCOL_TCP\x10\x01\x12 \n" +
	"\x1cHELPER_NETWORK_PROTOCOL_HTTP\x10\x02\x12!\n" +
	"\x1dHELPER_NETWORK_PROTOCOL_HTTPS\x10\x03B_Z]github.com/SecondStack-AI/SecondBox/runner/internal/microsandboxprotocol;microsandboxprotocolb\x06proto3"

var (
	file_microsandbox_helper_v1_helper_proto_rawDescOnce sync.Once
	file_microsandbox_helper_v1_helper_proto_rawDescData []byte
)

func file_microsandbox_helper_v1_helper_proto_rawDescGZIP() []byte {
	file_microsandbox_helper_v1_helper_proto_rawDescOnce.Do(func() {
		file_microsandbox_helper_v1_helper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_microsandbox_helper_v1_helper_proto_rawDesc), len(file_microsandbox_helper_v1_helper_proto_rawDesc)))
	})
	return file_microsandbox_helper_v1_helper_proto_rawDescData
}

var file_microsandbox_helper_v1_helper_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_microsandbox_helper_v1_helper_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_microsandbox_helper_v1_helper_proto_goTypes = []any{
	(Operation)(0),                   // 0: secondbox.microsandbox.helper.v1.Operation
	(HelperNetworkPolicyMode)(0),     // 1: secondbox.microsandbox.helper.v1.HelperNetworkPolicyMode
	(HelperNetworkProtocol)(0),       // 2: secondbox.microsandbox.helper.v1.HelperNetworkProtocol
	(*Envelope)(nil),                 // 3: secondbox.microsandbox.helper.v1.Envelope
	(*StartRequest)(nil),             // 4: secondbox.microsandbox.helper.v1.StartRequest
	(*HelperNetworkDestination)(nil), // 5: secondbox.microsandbox.helper.v1.HelperNetworkDestination
	(*HelperNetworkPolicy)(nil),      // 6: secondbox.microsandbox.helper.v1.HelperNetworkPolicy
	(*ReadyEvent)(nil),               // 7: secondbox.microsandbox.helper.v1.ReadyEvent
	(*ExecRequest)(nil),              // 8: secondbox.microsandbox.helper.v1.ExecRequest
	(*FileRequest)(nil),              // 9: secondbox.microsandbox.helper.v1.FileRequest
	(*PtyRequest)(nil),               // 10: secondbox.microsandbox.helper.v1.PtyRequest
	(*TcpRequest)(nil),               // 11: secondbox.microsandbox.helper.v1.TcpRequest
	(*ShutdownRequest)(nil),          // 12: secondbox.microsandbox.helper.v1.ShutdownRequest
	(*CancelRequest)(nil),            // 13: secondbox.microsandbox.helper.v1.CancelRequest
	(*StreamData)(nil),               // 14: secondbox.microsandbox.helper.v1.StreamData
	(*StreamCredit)(nil),             // 15: secondbox.microsandbox.helper.v1.StreamCredit
	(*TerminalEvent)(nil),            // 16: secondbox.microsandbox.helper.v1.TerminalEvent
	(*DiagnosticEvent)(nil),          // 17: secondbox.microsandbox.helper.v1.DiagnosticEvent
	(*FormatWorkspaceRequest)(nil),   // 18: secondbox.microsandbox.helper.v1.FormatWorkspaceRequest
}
var file_microsandbox_helper_v1_helper_proto_depIdxs = []int32{
	4,  // 0: secondbox.microsandbox.helper.v1.Envelope.start:type_name -> secondbox.microsandbox.helper.v1.StartRequest
	7,  // 1: secondbox.microsandbox.helper.v1.Envelope.ready:type_name -> secondbox.microsandbox.helper.v1.ReadyEvent
	8,  // 2: secondbox.microsandbox.helper.v1.Envelope.exec:type_name -> secondbox.microsandbox.helper.v1.ExecRequest
	9,  // 3: secondbox.microsandbox.helper.v1.Envelope.file:type_name -> secondbox.microsandbox.helper.v1.FileRequest
	10, // 4: secondbox.microsandbox.helper.v1.Envelope.pty:type_name -> secondbox.microsandbox.helper.v1.PtyRequest
	11, // 5: secondbox.microsandbox.helper.v1.Envelope.tcp:type_name -> secondbox.microsandbox.helper.v1.TcpRequest
	12, // 6: secondbox.microsandbox.helper.v1.Envelope.shutdown:type_name -> secondbox.microsandbox.helper.v1.ShutdownRequest
	13, // 7: secondbox.microsandbox.helper.v1.Envelope.cancel:type_name -> secondbox.microsandbox.helper.v1.CancelRequest
	14, // 8: secondbox.microsandbox.helper.v1.Envelope.stream_data:type_name -> secondbox.microsandbox.helper.v1.StreamData
	15, // 9: secondbox.microsandbox.helper.v1.Envelope.stream_credit:type_name -> secondbox.microsandbox.helper.v1.StreamCredit
	16, // 10: secondbox.microsandbox.helper.v1.Envelope.terminal:type_name -> secondbox.microsandbox.helper.v1.TerminalEvent
	17, // 11: secondbox.microsandbox.helper.v1.Envelope.diagnostic:type_name -> secondbox.microsandbox.helper.v1.DiagnosticEvent
	18, // 12: secondbox.microsandbox.helper.v1.Envelope.format_workspace:type_name -> secondbox.microsandbox.helper.v1.FormatWorkspaceRequest
	6,  // 13: secondbox.microsandbox.helper.v1.StartRequest.network_policy:type_name -> secondbox.microsandbox.helper.v1.HelperNetworkPolicy
	2,  // 14: secondbox.microsandbox.helper.v1.HelperNetworkDestination.protocol:type_name -> secondbox.microsandbox.helper.v1.HelperNetworkProtocol
	1,  // 15: secondbox.microsandbox.helper.v1.HelperNetworkPolicy.mode:type_name -> secondbox.microsandbox.helper.v1.HelperNetworkPolicyMode
	5,  // 16: secondbox.microsandbox.helper.v1.HelperNetworkPolicy.destinations:type_name -> secondbox.microsandbox.helper.v1.HelperNetworkDestination
	0,  // 17: secondbox.microsandbox.helper.v1.ReadyEvent.operations:type_name -> secondbox.microsandbox.helper.v1.Operation
	0,  // 18: secondbox.microsandbox.helper.v1.FileRequest.operation:type_name -> secondbox.microsandbox.helper.v1.Operation
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_microsandbox_helper_v1_helper_proto_init() }
func file_microsandbox_helper_v1_helper_proto_init() {
	if File_microsandbox_helper_v1_helper_proto != nil {
		return
	}
	file_microsandbox_helper_v1_helper_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Start)(nil),
		(*Envelope_Ready)(nil),
		(*Envelope_Exec)(nil),
		(*Envelope_File)(nil),
		(*Envelope_Pty)(nil),
		(*Envelope_Tcp)(nil),
		(*Envelope_Shutdown)(nil),
		(*Envelope_Cancel)(nil),
		(*Envelope_StreamData)(nil),
		(*Envelope_StreamCredit)(nil),
		(*Envelope_Terminal)(nil),
		(*Envelope_Diagnostic)(nil),
		(*Envelope_FormatWorkspace)(nil),
	}
	file_microsandbox_helper_v1_helper_proto_msgTypes[2].OneofWrappers = []any{
		(*HelperNetworkDestination_Domain)(nil),
		(*HelperNetworkDestination_Cidr)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_microsandbox_helper_v1_helper_proto_rawDesc), len(file_microsandbox_helper_v1_helper_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_microsandbox_helper_v1_helper_proto_goTypes,
		DependencyIndexes: file_microsandbox_helper_v1_helper_proto_depIdxs,
		EnumInfos:         file_microsandbox_helper_v1_helper_proto_enumTypes,
		MessageInfos:      file_microsandbox_helper_v1_helper_proto_msgTypes,
	}.Build()
	File_microsandbox_helper_v1_helper_proto = out.File
	file_microsandbox_helper_v1_helper_proto_goTypes = nil
	file_microsandbox_helper_v1_helper_proto_depIdxs = nil
}
