// Code generated by secondbox-sdkgen. DO NOT EDIT.

export type JSONValue =
  | null
  | boolean
  | number
  | string
  | readonly JSONValue[]
  | { readonly [key: string]: JSONValue };

export interface AcquireLeaseRequest {
  readonly durationSeconds: number;
  readonly replaceActive?: boolean;
}

export interface ArgvCommand {
  readonly arguments: readonly string[];
  readonly executable: string;
  readonly mode: "argv";
}

export interface Artifact {
  readonly createdAt: Timestamp;
  readonly expiresAt: Timestamp;
  readonly generation: number;
  readonly id: OpaqueID;
  readonly mediaType: string;
  readonly metadata: Metadata;
  readonly name: string;
  readonly sandboxId: OpaqueID;
  readonly sha256: string;
  readonly sizeBytes: number;
}

export interface ArtifactPage {
  readonly items: readonly Artifact[];
  readonly nextCursor?: string;
}

export type BootStage = "runner_admission" | "artifact_verify" | "workspace_attach" | "network_setup" | "compute_launch" | "guest_negotiation" | "ready";

export interface BootStageTiming {
  readonly cumulativeMilliseconds: number;
  readonly elapsedMilliseconds: number;
  readonly observedAt: Timestamp;
  readonly receivedAt: Timestamp;
  readonly stage: BootStage;
}

export interface BootStageTimingSummary {
  readonly duration: DurationPercentiles;
  readonly stage: BootStage;
}

export interface BootTiming {
  readonly completed: boolean;
  readonly durationMilliseconds: number;
  readonly generation: number;
  readonly stages: readonly BootStageTiming[];
}

export interface BufferedExecRequest {
  readonly command: Command;
  readonly cwd?: WorkspacePath;
  readonly deadlineMilliseconds: number;
  readonly environment: StringMap;
  readonly maximumOutputBytes: number;
  readonly stdinBase64?: string;
}

export type Command = ShellCommand | ArgvCommand;

export type CorrelationID = string;

export interface CreateDirectoryRequest {
  readonly path: WorkspacePath;
  readonly recursive: boolean;
}

export interface CreatePortSessionRequest {
  readonly durationSeconds: number;
  readonly name: string;
}

export interface CreateProfileRequest {
  readonly name: ProfileName;
  readonly spec: ProfileRevisionSpec;
}

export interface CreateRunnerPoolRequest {
  readonly architectures: RunnerArchitectureList;
  readonly capabilities: RunnerCapabilityList;
  readonly capacityPolicy: RunnerCapacityPolicy;
  readonly name: ProfileName;
  readonly state: RunnerPoolState;
}

export interface CreateSandboxRequest {
  readonly metadata: Metadata;
  readonly profile: ProfileName;
  readonly sourceSnapshotId?: OpaqueID;
}

export interface CreateSnapshotRequest {
  readonly metadata: Metadata;
  readonly name: string;
}

export interface CreateTerminalRequest {
  readonly columns: number;
  readonly command: Command;
  readonly cwd?: WorkspacePath;
  readonly deadlineMilliseconds: number;
  readonly detachable: boolean;
  readonly environment: StringMap;
  readonly rows: number;
}

export interface DeploymentTimingSummary {
  readonly api: DurationPercentiles;
  readonly apiSeries: readonly HTTPRouteTimingSummary[];
  readonly boot: DurationPercentiles;
  readonly bootStages: readonly BootStageTimingSummary[];
  readonly dominantBootStage?: BootStageTimingSummary;
  readonly exec: DurationPercentiles;
  readonly execSeries: readonly ExecTimingSummary[];
  readonly observedAt: Timestamp;
  readonly operations: readonly OperationTimingSummary[];
  readonly windowSeconds: number;
}

export interface DirectoryListing {
  readonly entries: readonly FileStat[];
  readonly path: WorkspacePath;
}

export interface DurationPercentiles {
  readonly count: number;
  readonly p50Milliseconds?: number;
  readonly p95Milliseconds?: number;
  readonly p99Milliseconds?: number;
}

export interface ExecCancelled {
  readonly kind: "cancelled";
  readonly output: ExecOutput;
}

export interface ExecDeadlineExceeded {
  readonly elapsedMilliseconds: number;
  readonly kind: "deadline_exceeded";
  readonly output: ExecOutput;
}

export interface ExecExited {
  readonly elapsedMilliseconds: number;
  readonly exitCode: number;
  readonly kind: "exited";
  readonly output: ExecOutput;
  readonly signal?: number;
}

export interface ExecInfrastructureFailed {
  readonly kind: "infrastructure_failed";
  readonly message: string;
  readonly reason: InfrastructureFailureKind;
  readonly retryable: boolean;
}

export type ExecOutcome = ExecExited | ExecSpawnFailed | ExecDeadlineExceeded | ExecCancelled | ExecOutputExhausted | ExecInfrastructureFailed;

export interface ExecOutput {
  readonly stderrBase64: string;
  readonly stdoutBase64: string;
}

export interface ExecOutputExhausted {
  readonly kind: "output_exhausted";
  readonly limitBytes: number;
  readonly output: ExecOutput;
}

export interface ExecSpawnFailed {
  readonly kind: "spawn_failed";
  readonly message: string;
  readonly reason: SpawnFailureKind;
}

export type ExecStreamFrame = StreamInputFrame | StreamOutputFrame | StreamCreditFrame | StreamSignalFrame | StreamCancelFrame | StreamOutcomeFrame;

export interface ExecStreamSession {
  readonly expiresAt: Timestamp;
  readonly generation: number;
  readonly id: OpaqueID;
  readonly sandboxId: OpaqueID;
  readonly state: SessionState;
  readonly subprotocol: "secondbox.exec.v1";
  readonly websocketUrl: string;
}

export interface ExecTiming {
  readonly completedAt: Timestamp;
  readonly createdAt: Timestamp;
  readonly elapsedMilliseconds: number;
  readonly mode: "buffered" | "streaming";
  readonly outcome: "exited" | "deadline_exceeded";
  readonly sessionId: OpaqueID;
}

export interface ExecTimingSummary {
  readonly duration: DurationPercentiles;
  readonly mode: "buffered" | "streaming";
  readonly outcome: "exited" | "deadline_exceeded";
}

export interface ExecutionPolicy {
  readonly dataPlaneTransport: "proxied" | "direct";
  readonly maximumBufferedOutputBytes: number;
  readonly maximumDeadlineMilliseconds: number;
  readonly maximumTransferBytes: number;
  readonly streamWindowBytes: number;
  readonly terminalDetachSeconds: number;
}

export interface FileExistsResult {
  readonly exists: boolean;
  readonly path: WorkspacePath;
}

export type FileKind = "file" | "directory" | "symbolic_link";

export interface FileStat {
  readonly kind: FileKind;
  readonly modifiedAt: Timestamp;
  readonly path: WorkspacePath;
  readonly sizeBytes: number;
}

export interface FileWriteResult {
  readonly path: WorkspacePath;
  readonly sha256: string;
  readonly sizeBytes: number;
}

export type GuestLiveness = "unknown" | "starting" | "ready" | "lost" | "stopped";

export interface HTTPRouteTimingSummary {
  readonly duration: DurationPercentiles;
  readonly route: string;
  readonly statusClass: "1xx" | "2xx" | "3xx" | "4xx" | "5xx" | "other";
}

export type InfrastructureFailureKind = "transport" | "admission" | "generation_fenced" | "lease_fenced" | "guest_agent" | "execution_node" | "service";

export interface Instance {
  readonly createdAt: Timestamp;
  readonly generation: number;
  readonly guestHeartbeatAt?: Timestamp;
  readonly guestLiveness: GuestLiveness;
  readonly id: OpaqueID;
  readonly readyAt?: Timestamp;
  readonly sandboxId: OpaqueID;
  readonly state: InstanceState;
  readonly stoppedAt?: Timestamp;
  readonly terminationReason?: InstanceTerminationReason;
  readonly updatedAt: Timestamp;
}

export type InstanceState = "starting" | "ready" | "draining" | "stopping" | "stopped" | "lost" | "failed";

export type InstanceTerminationReason = "requested_drain" | "requested_stop" | "idle_timeout" | "maximum_duration" | "guest_shutdown" | "resource_exhaustion" | "guest_agent_lost" | "runner_lost" | "startup_failed" | "fenced" | "internal_failure";

export interface Lease {
  readonly createdAt: Timestamp;
  readonly expiresAt: Timestamp;
  readonly generation: number;
  readonly id: OpaqueID;
  readonly sandboxId: OpaqueID;
  readonly state: LeaseState;
  readonly updatedAt: Timestamp;
}

export type LeaseState = "active" | "released" | "expired" | "fenced";

export interface LifecyclePolicy {
  readonly drainGraceSeconds: number;
  readonly idleSeconds: number;
  readonly initialState: "stopped" | "running";
  readonly leaseSeconds: number;
  readonly maximumDurationSeconds: number;
}

export type Metadata = Readonly<Record<string, string>>;

export interface NetworkDestination {
  readonly cidr?: string;
  readonly domain?: string;
  readonly port: number;
  readonly protocol: "tcp" | "http" | "https";
}

export interface NetworkPolicy {
  readonly destinations: readonly NetworkDestination[];
  readonly mode: "deny_all" | "allow_list";
}

export type OpaqueID = string;

export interface Operation {
  readonly completedAt?: Timestamp;
  readonly createdAt: Timestamp;
  readonly error?: Problem;
  readonly id: OpaqueID;
  readonly kind: OperationKind;
  readonly requestId: CorrelationID;
  readonly sandbox?: Sandbox;
  readonly sandboxId: OpaqueID;
  readonly snapshot?: Snapshot;
  readonly startedAt?: Timestamp;
  readonly state: OperationState;
  readonly updatedAt: Timestamp;
}

export type OperationKind = "create" | "start" | "drain" | "stop" | "delete" | "relocate" | "snapshot_create" | "snapshot_delete" | "snapshot_restore" | "cancel_exec" | "cancel_terminal";

export interface OperationStageTiming {
  readonly cumulativeMilliseconds: number;
  readonly elapsedMilliseconds: number;
  readonly observedAt: Timestamp;
  readonly stage: "durable_admission" | "workspace_ready" | "placement_ready" | "startup_dispatched" | "ready_projected";
}

export type OperationState = "pending" | "running" | "succeeded" | "failed" | "cancelled";

export interface OperationTiming {
  readonly boots: readonly BootTiming[];
  readonly completedAt?: Timestamp;
  readonly createdAt: Timestamp;
  readonly executionMilliseconds?: number;
  readonly kind: OperationKind;
  readonly operationId: OpaqueID;
  readonly orchestration: readonly OperationStageTiming[];
  readonly queueMilliseconds?: number;
  readonly sandboxId: OpaqueID;
  readonly startedAt?: Timestamp;
  readonly state: OperationState;
  readonly totalMilliseconds?: number;
}

export interface OperationTimingSummary {
  readonly execution: DurationPercentiles;
  readonly kind: OperationKind;
  readonly queue: DurationPercentiles;
  readonly state: OperationState;
  readonly total: DurationPercentiles;
}

export type OwnershipRef = string;

export interface PingResult {
  readonly generation: number;
  readonly healthy: boolean;
  readonly observedAt: Timestamp;
  readonly sandboxId: OpaqueID;
}

export interface PortPolicy {
  readonly maximumSessionSeconds: number;
  readonly maximumSessions: number;
  readonly name: string;
  readonly port: number;
  readonly protocol: "tcp" | "http";
}

export interface PortSession {
  readonly certificateSpkiSha256?: string;
  readonly createdAt: Timestamp;
  readonly endpoint: string;
  readonly expiresAt: Timestamp;
  readonly generation: number;
  readonly id: OpaqueID;
  readonly name: string;
  readonly protocol: "tcp" | "http";
  readonly sandboxId: OpaqueID;
  readonly state: "open" | "closing" | "closed" | "expired" | "fenced";
  readonly transport: "relay" | "direct";
}

export interface Problem {
  readonly code: ProblemCode;
  readonly details?: readonly ProblemDetail[];
  readonly requestId: CorrelationID;
  readonly retryAfterMilliseconds?: number;
  readonly retryable: boolean;
  readonly status: number;
  readonly title: string;
  readonly type: string;
}

export type ProblemCode = "invalid_request" | "authentication_failed" | "authorization_failed" | "not_found" | "idempotency_conflict" | "precondition_failed" | "state_conflict" | "workspace_mutation_conflict" | "generation_fenced" | "lease_fenced" | "profile_unavailable" | "home_runner_unavailable" | "sandbox_not_stopped" | "workspace_relocation_snapshots_present" | "workspace_relocation_target_unavailable" | "quota_exceeded" | "limit_exceeded" | "guest_unavailable" | "execution_node_unavailable" | "dependency_unavailable" | "internal_error" | "terminal_replay_evicted" | "wait_expired";

export interface ProblemDetail {
  readonly field: string;
  readonly reason: string;
}

export interface Profile {
  readonly createdAt: Timestamp;
  readonly currentRevision: ProfileRevision;
  readonly name: ProfileName;
  readonly revision: number;
  readonly state: ProfileState;
  readonly updatedAt: Timestamp;
}

export type ProfileName = string;

export interface ProfilePage {
  readonly items: readonly Profile[];
  readonly nextCursor?: string;
}

export interface ProfileRevision {
  readonly createdAt: Timestamp;
  readonly id: OpaqueID;
  readonly number: number;
  readonly spec: ProfileRevisionSpec;
}

export interface ProfileRevisionSpec {
  readonly architecture: "amd64" | "arm64";
  readonly execution: ExecutionPolicy;
  readonly lifecycle: LifecyclePolicy;
  readonly network: NetworkPolicy;
  readonly pool: string;
  readonly ports: readonly PortPolicy[];
  readonly resources: ResourcePolicy;
  readonly retention: RetentionPolicy;
  readonly runtimeBundleDigest: string;
  readonly toolchainBundleDigest: string;
}

export type ProfileState = "enabled" | "disabled";

export interface RelocateSandboxRequest {
  readonly runnerPool?: ProfileName;
  readonly targetRunnerId?: RunnerID;
}

export interface RemovePathRequest {
  readonly force: boolean;
  readonly path: WorkspacePath;
  readonly recursive: boolean;
}

export interface RenewLeaseRequest {
  readonly durationSeconds: number;
}

export interface ResourcePolicy {
  readonly concurrentOperations: number;
  readonly cpuMillis: number;
  readonly memoryBytes: number;
  readonly processLimit: number;
  readonly workspaceBytes: number;
}

export interface RestoreSnapshotRequest {
  readonly snapshotId: OpaqueID;
}

export interface RetentionPolicy {
  readonly artifactRetentionSeconds: number;
  readonly snapshotLimit: number;
  readonly snapshotRetentionSeconds: number;
}

export interface ReviseProfileRequest {
  readonly spec: ProfileRevisionSpec;
}

export interface Runner {
  readonly architectures: readonly ("amd64" | "arm64")[];
  readonly capabilities: readonly ("compute" | "network-policy" | "storage" | "cleanup" | "local-workspace" | "exec-streaming" | "file-streaming" | "pty" | "port-proxy" | "evidence")[];
  readonly capacity: Readonly<Record<string, number>>;
  readonly createdAt: Timestamp;
  readonly credentialState: "pre_shared";
  readonly id: RunnerID;
  readonly lastSeenAt?: Timestamp;
  readonly name: string;
  readonly poolName: ProfileName;
  readonly protocolVersions: readonly string[];
  readonly revision: number;
  readonly sandboxStartP95Milliseconds: number;
  readonly sandboxStartSampleCount: number;
  readonly state: "enrolling" | "enrolled" | "connected" | "ready" | "draining" | "drained" | "offline";
  readonly updatedAt: Timestamp;
}

export type RunnerArchitectureList = readonly ("amd64" | "arm64")[];

export type RunnerCapabilityList = readonly ("compute" | "network-policy" | "storage" | "cleanup" | "local-workspace" | "workspace-relocation" | "exec-streaming" | "file-streaming" | "pty" | "port-proxy" | "evidence")[];

export type RunnerCapacityPolicy = Readonly<Record<string, number>>;

export type RunnerID = string;

export interface RunnerPage {
  readonly items: readonly Runner[];
  readonly nextCursor?: string;
}

export interface RunnerPool {
  readonly architectures: RunnerArchitectureList;
  readonly capabilities: RunnerCapabilityList;
  readonly capacityPolicy: RunnerCapacityPolicy;
  readonly createdAt: Timestamp;
  readonly name: ProfileName;
  readonly readyRunnerCount: number;
  readonly revision: number;
  readonly state: RunnerPoolState;
  readonly updatedAt: Timestamp;
}

export interface RunnerPoolPage {
  readonly items: readonly RunnerPool[];
  readonly nextCursor?: string;
}

export type RunnerPoolState = "ready" | "draining" | "offline";

export interface Sandbox {
  readonly createdAt: Timestamp;
  readonly deletedAt?: Timestamp;
  readonly desiredState: SandboxDesiredState;
  readonly generation: number;
  readonly id: OpaqueID;
  readonly instance?: Instance;
  readonly lastActivityAt?: Timestamp;
  readonly metadata: Metadata;
  readonly profile: ProfileName;
  readonly profileRevisionId: OpaqueID;
  readonly revision: number;
  readonly state: SandboxState;
  readonly updatedAt: Timestamp;
  readonly workspace: Workspace;
}

export type SandboxDesiredState = "running" | "stopped" | "deleted";

export interface SandboxInspection {
  readonly activeSessions: number;
  readonly generation: number;
  readonly guestHealthy: boolean;
  readonly observedAt: Timestamp;
  readonly sandboxId: OpaqueID;
}

export interface SandboxPage {
  readonly items: readonly Sandbox[];
  readonly nextCursor?: string;
}

export type SandboxState = "creating" | "stopped" | "starting" | "ready" | "draining" | "stopping" | "failed" | "deleting" | "deleted";

export interface SandboxTiming {
  readonly execs: readonly ExecTiming[];
  readonly operations: readonly OperationTiming[];
  readonly sandboxId: OpaqueID;
}

export type SessionState = "open" | "detached" | "closing" | "closed";

export interface ShellCommand {
  readonly command: string;
  readonly mode: "shell";
}

export interface Snapshot {
  readonly createdAt: Timestamp;
  readonly expiresAt?: Timestamp;
  readonly generation: number;
  readonly id: OpaqueID;
  readonly metadata: Metadata;
  readonly name: string;
  readonly sandboxId: OpaqueID;
  readonly sizeBytes: number;
  readonly state: "creating" | "ready" | "deleting" | "failed";
}

export interface SnapshotPage {
  readonly items: readonly Snapshot[];
  readonly nextCursor?: string;
}

export type SpawnFailureKind = "not_found" | "permission_denied" | "invalid_cwd" | "malformed_executable";

export interface StreamCancelFrame {
  readonly sequence: number;
  readonly type: "cancel";
}

export interface StreamCreditFrame {
  readonly bytes: number;
  readonly sequence: number;
  readonly type: "credit";
}

export interface StreamInputFrame {
  readonly dataBase64: string;
  readonly endOfInput: boolean;
  readonly sequence: number;
  readonly type: "stdin";
}

export interface StreamOutcomeFrame {
  readonly outcome: ExecOutcome;
  readonly sequence: number;
  readonly type: "outcome";
}

export interface StreamOutputFrame {
  readonly dataBase64: string;
  readonly sequence: number;
  readonly stream: "stdout" | "stderr";
  readonly type: "output";
}

export interface StreamSignalFrame {
  readonly sequence: number;
  readonly signal: number;
  readonly type: "signal";
}

export interface StreamingExecRequest {
  readonly command: Command;
  readonly cwd?: WorkspacePath;
  readonly deadlineMilliseconds: number;
  readonly environment: StringMap;
  readonly maximumOutputBytes: number;
  readonly windowBytes: number;
}

export type StringMap = Readonly<Record<string, string>>;

export type TerminalFrame = TerminalInputFrame | TerminalOutputFrame | TerminalResizeFrame | StreamCreditFrame | StreamCancelFrame | StreamOutcomeFrame;

export interface TerminalInputFrame {
  readonly dataBase64: string;
  readonly sequence: number;
  readonly type: "terminal_input";
}

export interface TerminalOutputFrame {
  readonly dataBase64: string;
  readonly sequence: number;
  readonly type: "terminal_output";
}

export interface TerminalResizeFrame {
  readonly columns: number;
  readonly rows: number;
  readonly sequence: number;
  readonly type: "resize";
}

export interface TerminalSession {
  readonly expiresAt: Timestamp;
  readonly generation: number;
  readonly id: OpaqueID;
  readonly nextClientSequence: number;
  readonly sandboxId: OpaqueID;
  readonly state: SessionState;
  readonly streamWindowBytes: number;
  readonly subprotocol: "secondbox.terminal.v1";
  readonly websocketUrl: string;
}

export type Timestamp = string;

export interface TouchResult {
  readonly generation: number;
  readonly lastActivityAt: Timestamp;
  readonly sandboxId: OpaqueID;
}

export interface UpdateRunnerPoolRequest {
  readonly architectures?: RunnerArchitectureList;
  readonly capabilities?: RunnerCapabilityList;
  readonly capacityPolicy?: RunnerCapacityPolicy;
  readonly state?: RunnerPoolState;
}

export interface UpdateSandboxMetadataRequest {
  readonly metadata: Metadata;
}

export interface UploadArtifactRequest {
  readonly content: string;
  readonly mediaType: string;
  readonly metadata: Metadata;
  readonly name: string;
  readonly sha256: string;
}

export interface WaitSandboxRequest {
  readonly deadlineMilliseconds: number;
  readonly states: readonly SandboxState[];
}

export interface Workspace {
  readonly createdAt: Timestamp;
  readonly generation: number;
  readonly id: OpaqueID;
  readonly sizeBytes: number;
  readonly state: "creating" | "ready" | "deleting" | "deleted" | "failed";
  readonly updatedAt: Timestamp;
}

export type WorkspacePath = string;

export type OperationID =
  | "acquireSandboxLease"
  | "cancelSandboxExecStream"
  | "cancelSandboxTerminal"
  | "closeSandboxPortSession"
  | "createProfile"
  | "createRunnerPool"
  | "createSandbox"
  | "createSandboxDirectory"
  | "createSandboxExecStream"
  | "createSandboxPortSession"
  | "createSandboxSnapshot"
  | "createSandboxTerminal"
  | "deleteArtifact"
  | "deleteSandbox"
  | "deleteSnapshot"
  | "disableProfile"
  | "downloadArtifactContent"
  | "drainSandbox"
  | "executeSandboxCommand"
  | "getArtifact"
  | "getDeploymentTiming"
  | "getOperation"
  | "getOperationTiming"
  | "getProfile"
  | "getRunner"
  | "getRunnerPool"
  | "getSandbox"
  | "getSandboxLease"
  | "getSandboxPortSession"
  | "getSandboxTiming"
  | "getSnapshot"
  | "inspectSandbox"
  | "listProfiles"
  | "listRunnerPools"
  | "listRunners"
  | "listSandboxArtifacts"
  | "listSandboxDirectory"
  | "listSandboxSnapshots"
  | "listSandboxes"
  | "pingSandbox"
  | "readSandboxFile"
  | "reconnectSandboxTerminal"
  | "releaseSandboxLease"
  | "relocateSandbox"
  | "removeSandboxPath"
  | "renewSandboxLease"
  | "restoreSandboxSnapshot"
  | "reviseProfile"
  | "sandboxFileExists"
  | "startSandbox"
  | "statSandboxFile"
  | "stopSandbox"
  | "touchSandbox"
  | "updateRunnerPool"
  | "updateSandboxMetadata"
  | "uploadSandboxArtifact"
  | "waitForSandbox"
  | "writeSandboxFile";

export type Route = {
  readonly method: string;
  readonly path: string;
  readonly contentType?: string;
};

export const OPERATIONS: Readonly<Record<OperationID, Route>> = {
  acquireSandboxLease: { method: "POST", path: "/v1/sandboxes/{sandboxId}/leases", contentType: "application/json" },
  cancelSandboxExecStream: { method: "POST", path: "/v1/sandboxes/{sandboxId}/exec-streams/{execSessionId}:cancel" },
  cancelSandboxTerminal: { method: "DELETE", path: "/v1/sandboxes/{sandboxId}/terminals/{terminalSessionId}" },
  closeSandboxPortSession: { method: "DELETE", path: "/v1/sandboxes/{sandboxId}/port-sessions/{portSessionId}" },
  createProfile: { method: "POST", path: "/v1/profiles", contentType: "application/json" },
  createRunnerPool: { method: "POST", path: "/v1/runner-pools", contentType: "application/json" },
  createSandbox: { method: "POST", path: "/v1/sandboxes", contentType: "application/json" },
  createSandboxDirectory: { method: "POST", path: "/v1/sandboxes/{sandboxId}/directories", contentType: "application/json" },
  createSandboxExecStream: { method: "POST", path: "/v1/sandboxes/{sandboxId}/exec-streams", contentType: "application/json" },
  createSandboxPortSession: { method: "POST", path: "/v1/sandboxes/{sandboxId}/port-sessions", contentType: "application/json" },
  createSandboxSnapshot: { method: "POST", path: "/v1/sandboxes/{sandboxId}/snapshots", contentType: "application/json" },
  createSandboxTerminal: { method: "POST", path: "/v1/sandboxes/{sandboxId}/terminals", contentType: "application/json" },
  deleteArtifact: { method: "DELETE", path: "/v1/artifacts/{artifactId}" },
  deleteSandbox: { method: "DELETE", path: "/v1/sandboxes/{sandboxId}" },
  deleteSnapshot: { method: "DELETE", path: "/v1/snapshots/{snapshotId}" },
  disableProfile: { method: "POST", path: "/v1/profiles/{profileName}:disable" },
  downloadArtifactContent: { method: "GET", path: "/v1/artifacts/{artifactId}/content" },
  drainSandbox: { method: "POST", path: "/v1/sandboxes/{sandboxId}:drain" },
  executeSandboxCommand: { method: "POST", path: "/v1/sandboxes/{sandboxId}/exec", contentType: "application/json" },
  getArtifact: { method: "GET", path: "/v1/artifacts/{artifactId}" },
  getDeploymentTiming: { method: "GET", path: "/v1/timings" },
  getOperation: { method: "GET", path: "/v1/operations/{operationId}" },
  getOperationTiming: { method: "GET", path: "/v1/operations/{operationId}/timings" },
  getProfile: { method: "GET", path: "/v1/profiles/{profileName}" },
  getRunner: { method: "GET", path: "/v1/runners/{runnerId}" },
  getRunnerPool: { method: "GET", path: "/v1/runner-pools/{runnerPoolName}" },
  getSandbox: { method: "GET", path: "/v1/sandboxes/{sandboxId}" },
  getSandboxLease: { method: "GET", path: "/v1/leases/{leaseId}" },
  getSandboxPortSession: { method: "GET", path: "/v1/sandboxes/{sandboxId}/port-sessions/{portSessionId}" },
  getSandboxTiming: { method: "GET", path: "/v1/sandboxes/{sandboxId}/timings" },
  getSnapshot: { method: "GET", path: "/v1/snapshots/{snapshotId}" },
  inspectSandbox: { method: "POST", path: "/v1/sandboxes/{sandboxId}:inspect" },
  listProfiles: { method: "GET", path: "/v1/profiles" },
  listRunnerPools: { method: "GET", path: "/v1/runner-pools" },
  listRunners: { method: "GET", path: "/v1/runners" },
  listSandboxArtifacts: { method: "GET", path: "/v1/sandboxes/{sandboxId}/artifacts" },
  listSandboxDirectory: { method: "GET", path: "/v1/sandboxes/{sandboxId}/directories" },
  listSandboxSnapshots: { method: "GET", path: "/v1/sandboxes/{sandboxId}/snapshots" },
  listSandboxes: { method: "GET", path: "/v1/sandboxes" },
  pingSandbox: { method: "POST", path: "/v1/sandboxes/{sandboxId}:ping" },
  readSandboxFile: { method: "GET", path: "/v1/sandboxes/{sandboxId}/files" },
  reconnectSandboxTerminal: { method: "GET", path: "/v1/sandboxes/{sandboxId}/terminals/{terminalSessionId}" },
  releaseSandboxLease: { method: "DELETE", path: "/v1/leases/{leaseId}" },
  relocateSandbox: { method: "POST", path: "/v1/sandboxes/{sandboxId}:relocate", contentType: "application/json" },
  removeSandboxPath: { method: "DELETE", path: "/v1/sandboxes/{sandboxId}/directories", contentType: "application/json" },
  renewSandboxLease: { method: "POST", path: "/v1/leases/{leaseId}:renew", contentType: "application/json" },
  restoreSandboxSnapshot: { method: "POST", path: "/v1/sandboxes/{sandboxId}:restore", contentType: "application/json" },
  reviseProfile: { method: "POST", path: "/v1/profiles/{profileName}:revise", contentType: "application/json" },
  sandboxFileExists: { method: "GET", path: "/v1/sandboxes/{sandboxId}/files:exists" },
  startSandbox: { method: "POST", path: "/v1/sandboxes/{sandboxId}:start" },
  statSandboxFile: { method: "GET", path: "/v1/sandboxes/{sandboxId}/files:stat" },
  stopSandbox: { method: "POST", path: "/v1/sandboxes/{sandboxId}:stop" },
  touchSandbox: { method: "POST", path: "/v1/sandboxes/{sandboxId}:touch" },
  updateRunnerPool: { method: "PATCH", path: "/v1/runner-pools/{runnerPoolName}", contentType: "application/json" },
  updateSandboxMetadata: { method: "PUT", path: "/v1/sandboxes/{sandboxId}/metadata", contentType: "application/json" },
  uploadSandboxArtifact: { method: "POST", path: "/v1/sandboxes/{sandboxId}/artifacts", contentType: "multipart/form-data" },
  waitForSandbox: { method: "POST", path: "/v1/sandboxes/{sandboxId}:wait", contentType: "application/json" },
  writeSandboxFile: { method: "PUT", path: "/v1/sandboxes/{sandboxId}/files", contentType: "application/octet-stream" },
};
