package deployconfig

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"

	deployassets "github.com/SecondStack-AI/SecondBox/deploy"
)

const generatedEnvironmentHeader = "# Generated by secondbox-deploy. DO NOT EDIT.\n"

const dataPlaneRetentionHelp = "Data-plane session, result, and idempotency retention deadline."

// Render resolves the manifest and atomically replaces generated environment
// artifacts. The manifest and its referenced secret files remain authoritative.
func Render(manifestPath, environmentPath string) (ResolvedDeployment, error) {
	resolved, err := Resolve(manifestPath)
	if err != nil {
		return ResolvedDeployment{}, err
	}
	content, err := EncodeComposeEnvironment(resolved.Environment)
	if err != nil {
		return ResolvedDeployment{}, err
	}
	if err := writeAtomic(environmentPath, content, 0o600, true); err != nil {
		return ResolvedDeployment{}, manifestError("write generated environment", err)
	}
	runnerDirectory := environmentPath + ".runners"
	if len(resolved.RemoteRunnerEnvironment) != 0 {
		if err := ensurePrivateDirectory(runnerDirectory); err != nil {
			return ResolvedDeployment{}, manifestError("create remote runner artifact directory", err)
		}
		for runnerID, environment := range resolved.RemoteRunnerEnvironment {
			encoded, err := EncodeSystemdEnvironment(environment)
			if err != nil {
				return ResolvedDeployment{}, err
			}
			if err := writeAtomic(filepath.Join(runnerDirectory, runnerID+".env"), encoded, 0o600, true); err != nil {
				return ResolvedDeployment{}, manifestError("write remote runner environment for "+runnerID, err)
			}
		}
	}
	if err := removeStaleRunnerArtifacts(runnerDirectory, resolved.RemoteRunnerEnvironment); err != nil {
		return ResolvedDeployment{}, manifestError("reconcile remote runner artifacts", err)
	}
	composeFiles, err := materializeComposeFiles(environmentPath, resolved.ComposeFiles)
	if err != nil {
		return ResolvedDeployment{}, err
	}
	resolved.ComposeFiles = composeFiles
	return resolved, nil
}

func materializeComposeFiles(environmentPath string, selected []string) ([]string, error) {
	absoluteEnvironment, err := filepath.Abs(environmentPath)
	if err != nil {
		return nil, manifestError("resolve generated Compose asset directory", err)
	}
	directory := absoluteEnvironment + ".compose"
	if err := ensurePrivateDirectory(directory); err != nil {
		return nil, manifestError("create generated Compose asset directory", err)
	}
	materialized := make([]string, 0, len(selected))
	for _, logicalPath := range selected {
		content, err := deployassets.ReadComposeFile(logicalPath)
		if err != nil {
			return nil, err
		}
		path := filepath.Join(directory, filepath.Base(logicalPath))
		if err := writeAtomic(path, content, 0o600, true); err != nil {
			return nil, manifestError("write generated Compose asset "+logicalPath, err)
		}
		materialized = append(materialized, path)
	}
	return materialized, nil
}

func removeStaleRunnerArtifacts(directory string, desired map[string]map[string]string) error {
	directoryInfo, err := os.Lstat(directory)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return err
	}
	if !directoryInfo.IsDir() || directoryInfo.Mode()&os.ModeSymlink != 0 {
		return fmt.Errorf("%s must be a non-symbolic-link directory", directory)
	}
	if directoryInfo.Mode().Perm()&0o077 != 0 {
		return fmt.Errorf("%s must not grant group or other access", directory)
	}
	entries, err := os.ReadDir(directory)
	if err != nil {
		return err
	}
	for _, entry := range entries {
		if entry.Type()&os.ModeSymlink != 0 || !entry.Type().IsRegular() || !strings.HasSuffix(entry.Name(), ".env") {
			return fmt.Errorf("refusing unexpected entry %s", entry.Name())
		}
		runnerID := strings.TrimSuffix(entry.Name(), ".env")
		if _, exists := desired[runnerID]; exists {
			continue
		}
		path := filepath.Join(directory, entry.Name())
		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if !bytes.HasPrefix(content, []byte(generatedEnvironmentHeader)) {
			return fmt.Errorf("refusing non-generated stale artifact %s", entry.Name())
		}
		if err := os.Remove(path); err != nil {
			return err
		}
	}
	remaining, err := os.ReadDir(directory)
	if err != nil {
		return err
	}
	if len(remaining) == 0 {
		if err := os.Remove(directory); err != nil {
			return err
		}
		return syncDirectory(filepath.Dir(directory))
	}
	return syncDirectory(directory)
}

func EncodeComposeEnvironment(environment map[string]string) ([]byte, error) {
	var output bytes.Buffer
	output.WriteString(generatedEnvironmentHeader)
	for _, name := range sortedKeys(environment) {
		value := environment[name]
		if strings.ContainsAny(name, "=\x00\r\n") || name == "" {
			return nil, manifestError("invalid generated environment name", nil)
		}
		if strings.ContainsAny(value, "\x00\r\n") {
			return nil, manifestError("generated Compose environment value for "+name+" contains a forbidden byte", nil)
		}
		// Compose treats single-quoted env-file values literally. Backslash-quote
		// is its only escape in that grammar.
		output.WriteString(name)
		output.WriteString("='")
		output.WriteString(strings.ReplaceAll(value, "'", "\\'"))
		output.WriteString("'\n")
	}
	return output.Bytes(), nil
}

func EncodeSystemdEnvironment(environment map[string]string) ([]byte, error) {
	var output bytes.Buffer
	output.WriteString(generatedEnvironmentHeader)
	for _, name := range sortedKeys(environment) {
		value := environment[name]
		if strings.ContainsAny(name, "=\x00\r\n") || name == "" || strings.ContainsAny(value, "\x00\r\n") {
			return nil, manifestError("invalid generated systemd environment value for "+name, nil)
		}
		value = strings.ReplaceAll(value, "\\", "\\\\")
		value = strings.ReplaceAll(value, "\"", "\\\"")
		output.WriteString(name)
		output.WriteString("=\"")
		output.WriteString(value)
		output.WriteString("\"\n")
	}
	return output.Bytes(), nil
}

type Inspection struct {
	SchemaVersion          int                        `json:"schemaVersion"`
	Mode                   string                     `json:"mode"`
	DevelopmentWaitSeconds int64                      `json:"developmentWaitSeconds,omitempty"`
	ComposeFiles           []string                   `json:"composeFiles"`
	Environment            map[string]string          `json:"environment"`
	Policy                 []InspectedPolicy          `json:"policy"`
	Overrides              []InspectedOverride        `json:"overrides"`
	RemoteRunners          []string                   `json:"remoteRunners"`
	StandardBundles        []string                   `json:"standardBundles"`
	StandardProfiles       []InspectedStandardProfile `json:"standardProfiles"`
}

type InspectedStandardProfile struct {
	Name       string `json:"name"`
	Revision   int64  `json:"revision"`
	SpecDigest string `json:"specDigest"`
}

type InspectedPolicy struct {
	Name        string `json:"name"`
	Environment string `json:"environment"`
	Value       string `json:"value"`
	Help        string `json:"help"`
}

type InspectedOverride struct {
	Name        string `json:"name"`
	Environment string `json:"environment"`
	Default     string `json:"codeDefault"`
	Selected    bool   `json:"selected"`
	Value       string `json:"value,omitempty"`
	Help        string `json:"help"`
}

func Inspect(manifestPath string) ([]byte, error) {
	resolved, err := Resolve(manifestPath)
	if err != nil {
		return nil, err
	}
	redacted := make(map[string]string, len(resolved.Environment))
	secretNames := map[string]bool{
		"SECONDBOX_PLATFORM_TOKEN": true, "SECONDBOX_RUNNER_CREDENTIAL": true,
		"SECONDBOX_APPLICATION_AUTHORITIES_JSON": true, "SECONDBOX_POSTGRES_PASSWORD": true,
		"SECONDBOX_DATABASE_URL": true, "SECONDBOX_OBJECT_STORE_ROOT_USER": true,
		"SECONDBOX_OBJECT_STORE_ROOT_PASSWORD": true, "SECONDBOX_RUNNER_CA_PRIVATE_KEY": true,
		"SECONDBOX_RUNNER_SERVER_PRIVATE_KEY": true, "SECONDBOX_OBJECT_STORE_MC_HOST": true,
	}
	secretPathNames := map[string]bool{
		"SECONDBOX_RUNNER_PKI_HOST_DIR":      true,
		"SECONDBOX_RUNNER_IDENTITY_HOST_DIR": true,
	}
	for name, value := range resolved.Environment {
		if secretNames[name] {
			redacted[name] = "<redacted:" + SecretFingerprint(value) + ">"
		} else if secretPathNames[name] {
			redacted[name] = "<redacted-path>"
		} else {
			redacted[name] = value
		}
	}
	overrides := make([]InspectedOverride, 0, 19)
	for _, definition := range OverrideRegistry() {
		value, selected := resolved.Environment[definition.Environment]
		item := InspectedOverride{Name: definition.TOMLName, Environment: definition.Environment, Default: definition.Default, Selected: selected, Help: definition.Help}
		if selected {
			item.Value = value
		}
		overrides = append(overrides, item)
	}
	remote := make([]string, 0, len(resolved.RemoteRunnerEnvironment))
	for id := range resolved.RemoteRunnerEnvironment {
		remote = append(remote, id)
	}
	sort.Strings(remote)
	waitSeconds := int64(0)
	if resolved.Manifest.Deployment.DevelopmentWaitSeconds != nil {
		waitSeconds = *resolved.Manifest.Deployment.DevelopmentWaitSeconds
	}
	policy := []InspectedPolicy{{
		Name:        "data_plane_retention_seconds",
		Environment: "SECONDBOX_DATA_PLANE_RETENTION_SECONDS",
		Value:       resolved.Environment["SECONDBOX_DATA_PLANE_RETENTION_SECONDS"],
		Help:        dataPlaneRetentionHelp,
	}}
	profiles := make([]InspectedStandardProfile, 0, len(resolved.ResourceDocument.Profiles))
	for _, profile := range resolved.ResourceDocument.Profiles {
		head := profile.Revisions[len(profile.Revisions)-1]
		profiles = append(profiles, InspectedStandardProfile{Name: profile.Name, Revision: head.Number, SpecDigest: head.SpecDigest})
	}
	return json.MarshalIndent(Inspection{SchemaVersion: 1, Mode: resolved.Manifest.Deployment.Mode, DevelopmentWaitSeconds: waitSeconds, ComposeFiles: resolved.ComposeFiles, Environment: redacted, Policy: policy, Overrides: overrides, RemoteRunners: remote, StandardBundles: slices.Clone(resolved.Manifest.StandardResources.Bundles), StandardProfiles: profiles}, "", "  ")
}

func ensurePrivateDirectory(path string) error {
	info, err := os.Lstat(path)
	if os.IsNotExist(err) {
		if err := os.Mkdir(path, 0o700); err != nil {
			return err
		}
		return syncDirectory(filepath.Dir(path))
	}
	if err != nil {
		return err
	}
	if !info.IsDir() || info.Mode()&os.ModeSymlink != 0 {
		return fmt.Errorf("%s must be a non-symbolic-link directory", path)
	}
	if info.Mode().Perm()&0o077 != 0 {
		return fmt.Errorf("%s must not grant group or other access", path)
	}
	return nil
}

func writeAtomic(path string, content []byte, mode os.FileMode, replace bool) error {
	absolute, err := filepath.Abs(path)
	if err != nil {
		return err
	}
	parent := filepath.Dir(absolute)
	parentInfo, err := os.Lstat(parent)
	if err != nil {
		return err
	}
	if !parentInfo.IsDir() || parentInfo.Mode()&os.ModeSymlink != 0 {
		return fmt.Errorf("parent must be a non-symbolic-link directory")
	}
	if info, err := os.Lstat(absolute); err == nil {
		if info.Mode()&os.ModeSymlink != 0 || !info.Mode().IsRegular() {
			return fmt.Errorf("target must be a regular non-symbolic-link file")
		}
		if !replace {
			return fmt.Errorf("target already exists")
		}
	} else if !os.IsNotExist(err) {
		return err
	}
	temporary, err := os.CreateTemp(parent, "."+filepath.Base(absolute)+".tmp-")
	if err != nil {
		return err
	}
	temporaryPath := temporary.Name()
	cleanup := true
	defer func() {
		if cleanup {
			_ = os.Remove(temporaryPath)
		}
	}()
	if err := temporary.Chmod(mode); err != nil {
		temporary.Close()
		return err
	}
	if _, err := temporary.Write(content); err != nil {
		temporary.Close()
		return err
	}
	if err := temporary.Sync(); err != nil {
		temporary.Close()
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	if err := os.Rename(temporaryPath, absolute); err != nil {
		return err
	}
	cleanup = false
	return syncDirectory(parent)
}

func syncDirectory(path string) error {
	directory, err := os.Open(path)
	if err != nil {
		return err
	}
	defer directory.Close()
	return directory.Sync()
}
