// Code generated by secondbox-sdkgen. DO NOT EDIT.

package secondboxclient

var operations = map[string]OperationMetadata{
	"acquireSandboxLease": {
		OperationID: "acquireSandboxLease", Method: "POST", PathTemplate: "/v1/sandboxes/{sandboxId}/leases",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "AcquireLeaseRequest"},
		},
		RequestBodyRequired: true,
	},
	"cancelSandboxExecStream": {
		OperationID: "cancelSandboxExecStream", Method: "POST", PathTemplate: "/v1/sandboxes/{sandboxId}/exec-streams/{execSessionId}:cancel",
	},
	"cancelSandboxTerminal": {
		OperationID: "cancelSandboxTerminal", Method: "DELETE", PathTemplate: "/v1/sandboxes/{sandboxId}/terminals/{terminalSessionId}",
	},
	"closeSandboxPortSession": {
		OperationID: "closeSandboxPortSession", Method: "DELETE", PathTemplate: "/v1/sandboxes/{sandboxId}/port-sessions/{portSessionId}",
	},
	"createProfile": {
		OperationID: "createProfile", Method: "POST", PathTemplate: "/v1/profiles",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "CreateProfileRequest"},
		},
		RequestBodyRequired: true,
	},
	"createRunnerPool": {
		OperationID: "createRunnerPool", Method: "POST", PathTemplate: "/v1/runner-pools",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "CreateRunnerPoolRequest"},
		},
		RequestBodyRequired: true,
	},
	"createSandbox": {
		OperationID: "createSandbox", Method: "POST", PathTemplate: "/v1/sandboxes",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "CreateSandboxRequest"},
		},
		RequestBodyRequired: true,
	},
	"createSandboxDirectory": {
		OperationID: "createSandboxDirectory", Method: "POST", PathTemplate: "/v1/sandboxes/{sandboxId}/directories",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "CreateDirectoryRequest"},
		},
		RequestBodyRequired: true,
	},
	"createSandboxExecStream": {
		OperationID: "createSandboxExecStream", Method: "POST", PathTemplate: "/v1/sandboxes/{sandboxId}/exec-streams",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "StreamingExecRequest"},
		},
		RequestBodyRequired: true,
	},
	"createSandboxPortSession": {
		OperationID: "createSandboxPortSession", Method: "POST", PathTemplate: "/v1/sandboxes/{sandboxId}/port-sessions",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "CreatePortSessionRequest"},
		},
		RequestBodyRequired: true,
	},
	"createSandboxSnapshot": {
		OperationID: "createSandboxSnapshot", Method: "POST", PathTemplate: "/v1/sandboxes/{sandboxId}/snapshots",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "CreateSnapshotRequest"},
		},
		RequestBodyRequired: true,
	},
	"createSandboxTerminal": {
		OperationID: "createSandboxTerminal", Method: "POST", PathTemplate: "/v1/sandboxes/{sandboxId}/terminals",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "CreateTerminalRequest"},
		},
		RequestBodyRequired: true,
	},
	"deleteArtifact": {
		OperationID: "deleteArtifact", Method: "DELETE", PathTemplate: "/v1/artifacts/{artifactId}",
	},
	"deleteSandbox": {
		OperationID: "deleteSandbox", Method: "DELETE", PathTemplate: "/v1/sandboxes/{sandboxId}",
	},
	"deleteSnapshot": {
		OperationID: "deleteSnapshot", Method: "DELETE", PathTemplate: "/v1/snapshots/{snapshotId}",
	},
	"disableProfile": {
		OperationID: "disableProfile", Method: "POST", PathTemplate: "/v1/profiles/{profileName}:disable",
	},
	"downloadArtifactContent": {
		OperationID: "downloadArtifactContent", Method: "GET", PathTemplate: "/v1/artifacts/{artifactId}/content",
	},
	"drainSandbox": {
		OperationID: "drainSandbox", Method: "POST", PathTemplate: "/v1/sandboxes/{sandboxId}:drain",
	},
	"executeSandboxCommand": {
		OperationID: "executeSandboxCommand", Method: "POST", PathTemplate: "/v1/sandboxes/{sandboxId}/exec",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "BufferedExecRequest"},
		},
		RequestBodyRequired: true,
	},
	"getArtifact": {
		OperationID: "getArtifact", Method: "GET", PathTemplate: "/v1/artifacts/{artifactId}",
	},
	"getDeploymentTiming": {
		OperationID: "getDeploymentTiming", Method: "GET", PathTemplate: "/v1/timings",
	},
	"getOperation": {
		OperationID: "getOperation", Method: "GET", PathTemplate: "/v1/operations/{operationId}",
	},
	"getOperationTiming": {
		OperationID: "getOperationTiming", Method: "GET", PathTemplate: "/v1/operations/{operationId}/timings",
	},
	"getProfile": {
		OperationID: "getProfile", Method: "GET", PathTemplate: "/v1/profiles/{profileName}",
	},
	"getRunner": {
		OperationID: "getRunner", Method: "GET", PathTemplate: "/v1/runners/{runnerId}",
	},
	"getRunnerPool": {
		OperationID: "getRunnerPool", Method: "GET", PathTemplate: "/v1/runner-pools/{runnerPoolName}",
	},
	"getSandbox": {
		OperationID: "getSandbox", Method: "GET", PathTemplate: "/v1/sandboxes/{sandboxId}",
	},
	"getSandboxLease": {
		OperationID: "getSandboxLease", Method: "GET", PathTemplate: "/v1/leases/{leaseId}",
	},
	"getSandboxPortSession": {
		OperationID: "getSandboxPortSession", Method: "GET", PathTemplate: "/v1/sandboxes/{sandboxId}/port-sessions/{portSessionId}",
	},
	"getSandboxTiming": {
		OperationID: "getSandboxTiming", Method: "GET", PathTemplate: "/v1/sandboxes/{sandboxId}/timings",
	},
	"getSnapshot": {
		OperationID: "getSnapshot", Method: "GET", PathTemplate: "/v1/snapshots/{snapshotId}",
	},
	"inspectSandbox": {
		OperationID: "inspectSandbox", Method: "POST", PathTemplate: "/v1/sandboxes/{sandboxId}:inspect",
	},
	"listProfiles": {
		OperationID: "listProfiles", Method: "GET", PathTemplate: "/v1/profiles",
	},
	"listRunnerPools": {
		OperationID: "listRunnerPools", Method: "GET", PathTemplate: "/v1/runner-pools",
	},
	"listRunners": {
		OperationID: "listRunners", Method: "GET", PathTemplate: "/v1/runners",
	},
	"listSandboxArtifacts": {
		OperationID: "listSandboxArtifacts", Method: "GET", PathTemplate: "/v1/sandboxes/{sandboxId}/artifacts",
	},
	"listSandboxDirectory": {
		OperationID: "listSandboxDirectory", Method: "GET", PathTemplate: "/v1/sandboxes/{sandboxId}/directories",
	},
	"listSandboxSnapshots": {
		OperationID: "listSandboxSnapshots", Method: "GET", PathTemplate: "/v1/sandboxes/{sandboxId}/snapshots",
	},
	"listSandboxes": {
		OperationID: "listSandboxes", Method: "GET", PathTemplate: "/v1/sandboxes",
	},
	"pingSandbox": {
		OperationID: "pingSandbox", Method: "POST", PathTemplate: "/v1/sandboxes/{sandboxId}:ping",
	},
	"readSandboxFile": {
		OperationID: "readSandboxFile", Method: "GET", PathTemplate: "/v1/sandboxes/{sandboxId}/files",
	},
	"reconnectSandboxTerminal": {
		OperationID: "reconnectSandboxTerminal", Method: "GET", PathTemplate: "/v1/sandboxes/{sandboxId}/terminals/{terminalSessionId}",
	},
	"releaseSandboxLease": {
		OperationID: "releaseSandboxLease", Method: "DELETE", PathTemplate: "/v1/leases/{leaseId}",
	},
	"relocateSandbox": {
		OperationID: "relocateSandbox", Method: "POST", PathTemplate: "/v1/sandboxes/{sandboxId}:relocate",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "RelocateSandboxRequest"},
		},
		RequestBodyRequired: true,
	},
	"removeSandboxPath": {
		OperationID: "removeSandboxPath", Method: "DELETE", PathTemplate: "/v1/sandboxes/{sandboxId}/directories",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "RemovePathRequest"},
		},
		RequestBodyRequired: true,
	},
	"renewSandboxLease": {
		OperationID: "renewSandboxLease", Method: "POST", PathTemplate: "/v1/leases/{leaseId}:renew",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "RenewLeaseRequest"},
		},
		RequestBodyRequired: true,
	},
	"restoreSandboxSnapshot": {
		OperationID: "restoreSandboxSnapshot", Method: "POST", PathTemplate: "/v1/sandboxes/{sandboxId}:restore",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "RestoreSnapshotRequest"},
		},
		RequestBodyRequired: true,
	},
	"reviseProfile": {
		OperationID: "reviseProfile", Method: "POST", PathTemplate: "/v1/profiles/{profileName}:revise",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "ReviseProfileRequest"},
		},
		RequestBodyRequired: true,
	},
	"sandboxFileExists": {
		OperationID: "sandboxFileExists", Method: "GET", PathTemplate: "/v1/sandboxes/{sandboxId}/files:exists",
	},
	"startSandbox": {
		OperationID: "startSandbox", Method: "POST", PathTemplate: "/v1/sandboxes/{sandboxId}:start",
	},
	"statSandboxFile": {
		OperationID: "statSandboxFile", Method: "GET", PathTemplate: "/v1/sandboxes/{sandboxId}/files:stat",
	},
	"stopSandbox": {
		OperationID: "stopSandbox", Method: "POST", PathTemplate: "/v1/sandboxes/{sandboxId}:stop",
	},
	"touchSandbox": {
		OperationID: "touchSandbox", Method: "POST", PathTemplate: "/v1/sandboxes/{sandboxId}:touch",
	},
	"updateRunnerPool": {
		OperationID: "updateRunnerPool", Method: "PATCH", PathTemplate: "/v1/runner-pools/{runnerPoolName}",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "UpdateRunnerPoolRequest"},
		},
		RequestBodyRequired: true,
	},
	"updateSandboxMetadata": {
		OperationID: "updateSandboxMetadata", Method: "PUT", PathTemplate: "/v1/sandboxes/{sandboxId}/metadata",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "UpdateSandboxMetadataRequest"},
		},
		RequestBodyRequired: true,
	},
	"uploadSandboxArtifact": {
		OperationID: "uploadSandboxArtifact", Method: "POST", PathTemplate: "/v1/sandboxes/{sandboxId}/artifacts",
		RequestBody: []OperationMediaType{
			{ContentType: "multipart/form-data", Schema: "UploadArtifactRequest"},
		},
		RequestBodyRequired: true,
	},
	"waitForSandbox": {
		OperationID: "waitForSandbox", Method: "POST", PathTemplate: "/v1/sandboxes/{sandboxId}:wait",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "WaitSandboxRequest"},
		},
		RequestBodyRequired: true,
	},
	"writeSandboxFile": {
		OperationID: "writeSandboxFile", Method: "PUT", PathTemplate: "/v1/sandboxes/{sandboxId}/files",
		RequestBody: []OperationMediaType{
			{ContentType: "application/octet-stream", Schema: "string"},
		},
		RequestBodyRequired: true,
	},
}

// GetSandboxOperation is retained for callers that use the lower-level Do method.
var GetSandboxOperation = operations["getSandbox"]
