// Code generated by secondbox-sdkgen. DO NOT EDIT.

package secondboxclient

var operations = map[string]OperationMetadata{
	"acquireSandboxLease": {
		OperationID: "acquireSandboxLease", Method: "POST", PathTemplate: "/v1/sandboxes/{sandboxId}/leases",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "AcquireLeaseRequest"},
		},
		RequestBodyRequired: true,
	},
	"cancelSandboxExecStream": {
		OperationID: "cancelSandboxExecStream", Method: "POST", PathTemplate: "/v1/sandboxes/{sandboxId}/exec-streams/{execSessionId}:cancel",
	},
	"cancelSandboxTerminal": {
		OperationID: "cancelSandboxTerminal", Method: "DELETE", PathTemplate: "/v1/sandboxes/{sandboxId}/terminals/{terminalSessionId}",
	},
	"cleanupSubject": {
		OperationID: "cleanupSubject", Method: "POST", PathTemplate: "/v1/subjects/{subjectRef}:cleanup",
	},
	"closeSandboxPortSession": {
		OperationID: "closeSandboxPortSession", Method: "DELETE", PathTemplate: "/v1/sandboxes/{sandboxId}/port-sessions/{portSessionId}",
	},
	"closeSubject": {
		OperationID: "closeSubject", Method: "POST", PathTemplate: "/v1/subjects/{subjectRef}:close",
	},
	"createApplicationAuthority": {
		OperationID: "createApplicationAuthority", Method: "POST", PathTemplate: "/v1/application-authorities",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "CreateApplicationAuthorityRequest"},
		},
		RequestBodyRequired: true,
	},
	"createProfile": {
		OperationID: "createProfile", Method: "POST", PathTemplate: "/v1/profiles",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "CreateProfileRequest"},
		},
		RequestBodyRequired: true,
	},
	"createRunnerPool": {
		OperationID: "createRunnerPool", Method: "POST", PathTemplate: "/v1/runner-pools",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "CreateRunnerPoolRequest"},
		},
		RequestBodyRequired: true,
	},
	"createSandbox": {
		OperationID: "createSandbox", Method: "POST", PathTemplate: "/v1/sandboxes",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "CreateSandboxRequest"},
		},
		RequestBodyRequired: true,
	},
	"createSandboxDirectory": {
		OperationID: "createSandboxDirectory", Method: "POST", PathTemplate: "/v1/sandboxes/{sandboxId}/directories",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "CreateDirectoryRequest"},
		},
		RequestBodyRequired: true,
	},
	"createSandboxExecStream": {
		OperationID: "createSandboxExecStream", Method: "POST", PathTemplate: "/v1/sandboxes/{sandboxId}/exec-streams",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "StreamingExecRequest"},
		},
		RequestBodyRequired: true,
	},
	"createSandboxPortSession": {
		OperationID: "createSandboxPortSession", Method: "POST", PathTemplate: "/v1/sandboxes/{sandboxId}/port-sessions",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "CreatePortSessionRequest"},
		},
		RequestBodyRequired: true,
	},
	"createSandboxSnapshot": {
		OperationID: "createSandboxSnapshot", Method: "POST", PathTemplate: "/v1/sandboxes/{sandboxId}/snapshots",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "CreateSnapshotRequest"},
		},
		RequestBodyRequired: true,
	},
	"createSandboxTerminal": {
		OperationID: "createSandboxTerminal", Method: "POST", PathTemplate: "/v1/sandboxes/{sandboxId}/terminals",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "CreateTerminalRequest"},
		},
		RequestBodyRequired: true,
	},
	"createSubject": {
		OperationID: "createSubject", Method: "POST", PathTemplate: "/v1/subjects",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "CreateSubjectRequest"},
		},
		RequestBodyRequired: true,
	},
	"createTenant": {
		OperationID: "createTenant", Method: "POST", PathTemplate: "/v1/tenants",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "CreateTenantRequest"},
		},
		RequestBodyRequired: true,
	},
	"createTenantControllerAuthority": {
		OperationID: "createTenantControllerAuthority", Method: "POST", PathTemplate: "/v1/tenants/{tenantRef}/controller-authorities",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "CreateTenantControllerAuthorityRequest"},
		},
		RequestBodyRequired: true,
	},
	"deleteSandbox": {
		OperationID: "deleteSandbox", Method: "DELETE", PathTemplate: "/v1/sandboxes/{sandboxId}",
	},
	"deleteSnapshot": {
		OperationID: "deleteSnapshot", Method: "DELETE", PathTemplate: "/v1/snapshots/{snapshotId}",
	},
	"disableProfile": {
		OperationID: "disableProfile", Method: "POST", PathTemplate: "/v1/profiles/{profileName}:disable",
	},
	"drainSandbox": {
		OperationID: "drainSandbox", Method: "POST", PathTemplate: "/v1/sandboxes/{sandboxId}:drain",
	},
	"executeSandboxCommand": {
		OperationID: "executeSandboxCommand", Method: "POST", PathTemplate: "/v1/sandboxes/{sandboxId}/exec",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "BufferedExecRequest"},
		},
		RequestBodyRequired: true,
	},
	"getApplicationAuthority": {
		OperationID: "getApplicationAuthority", Method: "GET", PathTemplate: "/v1/application-authorities/{authorityId}",
	},
	"getDeploymentTiming": {
		OperationID: "getDeploymentTiming", Method: "GET", PathTemplate: "/v1/timings",
	},
	"getDeploymentUsage": {
		OperationID: "getDeploymentUsage", Method: "GET", PathTemplate: "/v1/deployment-usage",
	},
	"getOperation": {
		OperationID: "getOperation", Method: "GET", PathTemplate: "/v1/operations/{operationId}",
	},
	"getOperationTiming": {
		OperationID: "getOperationTiming", Method: "GET", PathTemplate: "/v1/operations/{operationId}/timings",
	},
	"getProfile": {
		OperationID: "getProfile", Method: "GET", PathTemplate: "/v1/profiles/{profileName}",
	},
	"getRunner": {
		OperationID: "getRunner", Method: "GET", PathTemplate: "/v1/runners/{runnerId}",
	},
	"getRunnerPool": {
		OperationID: "getRunnerPool", Method: "GET", PathTemplate: "/v1/runner-pools/{runnerPoolName}",
	},
	"getSandbox": {
		OperationID: "getSandbox", Method: "GET", PathTemplate: "/v1/sandboxes/{sandboxId}",
	},
	"getSandboxLease": {
		OperationID: "getSandboxLease", Method: "GET", PathTemplate: "/v1/leases/{leaseId}",
	},
	"getSandboxPortSession": {
		OperationID: "getSandboxPortSession", Method: "GET", PathTemplate: "/v1/sandboxes/{sandboxId}/port-sessions/{portSessionId}",
	},
	"getSandboxTiming": {
		OperationID: "getSandboxTiming", Method: "GET", PathTemplate: "/v1/sandboxes/{sandboxId}/timings",
	},
	"getSnapshot": {
		OperationID: "getSnapshot", Method: "GET", PathTemplate: "/v1/snapshots/{snapshotId}",
	},
	"getSubject": {
		OperationID: "getSubject", Method: "GET", PathTemplate: "/v1/subjects/{subjectRef}",
	},
	"getTenant": {
		OperationID: "getTenant", Method: "GET", PathTemplate: "/v1/tenants/{tenantRef}",
	},
	"getTenantControllerAuthority": {
		OperationID: "getTenantControllerAuthority", Method: "GET", PathTemplate: "/v1/tenants/{tenantRef}/controller-authorities/{authorityId}",
	},
	"getTenantUsage": {
		OperationID: "getTenantUsage", Method: "GET", PathTemplate: "/v1/usage",
	},
	"inspectSandbox": {
		OperationID: "inspectSandbox", Method: "POST", PathTemplate: "/v1/sandboxes/{sandboxId}:inspect",
	},
	"listApplicationAuthorities": {
		OperationID: "listApplicationAuthorities", Method: "GET", PathTemplate: "/v1/application-authorities",
	},
	"listProfiles": {
		OperationID: "listProfiles", Method: "GET", PathTemplate: "/v1/profiles",
	},
	"listRunnerPools": {
		OperationID: "listRunnerPools", Method: "GET", PathTemplate: "/v1/runner-pools",
	},
	"listRunners": {
		OperationID: "listRunners", Method: "GET", PathTemplate: "/v1/runners",
	},
	"listSandboxDirectory": {
		OperationID: "listSandboxDirectory", Method: "GET", PathTemplate: "/v1/sandboxes/{sandboxId}/directories",
	},
	"listSandboxSnapshots": {
		OperationID: "listSandboxSnapshots", Method: "GET", PathTemplate: "/v1/sandboxes/{sandboxId}/snapshots",
	},
	"listSandboxes": {
		OperationID: "listSandboxes", Method: "GET", PathTemplate: "/v1/sandboxes",
	},
	"listSubjects": {
		OperationID: "listSubjects", Method: "GET", PathTemplate: "/v1/subjects",
	},
	"listTenantControllerAuthorities": {
		OperationID: "listTenantControllerAuthorities", Method: "GET", PathTemplate: "/v1/tenants/{tenantRef}/controller-authorities",
	},
	"listTenants": {
		OperationID: "listTenants", Method: "GET", PathTemplate: "/v1/tenants",
	},
	"pingSandbox": {
		OperationID: "pingSandbox", Method: "POST", PathTemplate: "/v1/sandboxes/{sandboxId}:ping",
	},
	"reactivateTenant": {
		OperationID: "reactivateTenant", Method: "POST", PathTemplate: "/v1/tenants/{tenantRef}:reactivate",
	},
	"readSandboxFile": {
		OperationID: "readSandboxFile", Method: "GET", PathTemplate: "/v1/sandboxes/{sandboxId}/files",
	},
	"reconnectSandboxTerminal": {
		OperationID: "reconnectSandboxTerminal", Method: "GET", PathTemplate: "/v1/sandboxes/{sandboxId}/terminals/{terminalSessionId}",
	},
	"releaseSandboxLease": {
		OperationID: "releaseSandboxLease", Method: "DELETE", PathTemplate: "/v1/leases/{leaseId}",
	},
	"relocateSandbox": {
		OperationID: "relocateSandbox", Method: "POST", PathTemplate: "/v1/sandboxes/{sandboxId}:relocate",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "RelocateSandboxRequest"},
		},
		RequestBodyRequired: true,
	},
	"removeSandboxPath": {
		OperationID: "removeSandboxPath", Method: "DELETE", PathTemplate: "/v1/sandboxes/{sandboxId}/directories",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "RemovePathRequest"},
		},
		RequestBodyRequired: true,
	},
	"renewSandboxLease": {
		OperationID: "renewSandboxLease", Method: "POST", PathTemplate: "/v1/leases/{leaseId}:renew",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "RenewLeaseRequest"},
		},
		RequestBodyRequired: true,
	},
	"restoreSandboxSnapshot": {
		OperationID: "restoreSandboxSnapshot", Method: "POST", PathTemplate: "/v1/sandboxes/{sandboxId}:restore",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "RestoreSnapshotRequest"},
		},
		RequestBodyRequired: true,
	},
	"reviseProfile": {
		OperationID: "reviseProfile", Method: "POST", PathTemplate: "/v1/profiles/{profileName}:revise",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "ReviseProfileRequest"},
		},
		RequestBodyRequired: true,
	},
	"revokeApplicationAuthority": {
		OperationID: "revokeApplicationAuthority", Method: "POST", PathTemplate: "/v1/application-authorities/{authorityId}:revoke",
	},
	"revokeTenantControllerAuthority": {
		OperationID: "revokeTenantControllerAuthority", Method: "POST", PathTemplate: "/v1/tenants/{tenantRef}/controller-authorities/{authorityId}:revoke",
	},
	"rotateApplicationAuthority": {
		OperationID: "rotateApplicationAuthority", Method: "POST", PathTemplate: "/v1/application-authorities/{authorityId}:rotate",
	},
	"rotateTenantControllerAuthority": {
		OperationID: "rotateTenantControllerAuthority", Method: "POST", PathTemplate: "/v1/tenants/{tenantRef}/controller-authorities/{authorityId}:rotate",
	},
	"sandboxFileExists": {
		OperationID: "sandboxFileExists", Method: "GET", PathTemplate: "/v1/sandboxes/{sandboxId}/files:exists",
	},
	"startSandbox": {
		OperationID: "startSandbox", Method: "POST", PathTemplate: "/v1/sandboxes/{sandboxId}:start",
	},
	"statSandboxFile": {
		OperationID: "statSandboxFile", Method: "GET", PathTemplate: "/v1/sandboxes/{sandboxId}/files:stat",
	},
	"stopSandbox": {
		OperationID: "stopSandbox", Method: "POST", PathTemplate: "/v1/sandboxes/{sandboxId}:stop",
	},
	"suspendTenant": {
		OperationID: "suspendTenant", Method: "POST", PathTemplate: "/v1/tenants/{tenantRef}:suspend",
	},
	"touchSandbox": {
		OperationID: "touchSandbox", Method: "POST", PathTemplate: "/v1/sandboxes/{sandboxId}:touch",
	},
	"updateRunnerPool": {
		OperationID: "updateRunnerPool", Method: "PATCH", PathTemplate: "/v1/runner-pools/{runnerPoolName}",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "UpdateRunnerPoolRequest"},
		},
		RequestBodyRequired: true,
	},
	"updateSandboxMetadata": {
		OperationID: "updateSandboxMetadata", Method: "PUT", PathTemplate: "/v1/sandboxes/{sandboxId}/metadata",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "UpdateSandboxMetadataRequest"},
		},
		RequestBodyRequired: true,
	},
	"updateSubjectQuota": {
		OperationID: "updateSubjectQuota", Method: "PUT", PathTemplate: "/v1/subjects/{subjectRef}/quota",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "UpdateSubjectQuotaRequest"},
		},
		RequestBodyRequired: true,
	},
	"waitForSandbox": {
		OperationID: "waitForSandbox", Method: "POST", PathTemplate: "/v1/sandboxes/{sandboxId}:wait",
		RequestBody: []OperationMediaType{
			{ContentType: "application/json", Schema: "WaitSandboxRequest"},
		},
		RequestBodyRequired: true,
	},
	"writeSandboxFile": {
		OperationID: "writeSandboxFile", Method: "PUT", PathTemplate: "/v1/sandboxes/{sandboxId}/files",
		RequestBody: []OperationMediaType{
			{ContentType: "application/octet-stream", Schema: "string"},
		},
		RequestBodyRequired: true,
	},
}

// GetSandboxOperation is retained for callers that use the lower-level Do method.
var GetSandboxOperation = operations["getSandbox"]
