// Code generated by secondbox-sdkgen. DO NOT EDIT.

package secondboxclient

import (
	"time"

	"github.com/SecondStack-AI/SecondBox/pkg/contracts"
)

type AcquireLeaseRequest = contracts.AcquireLeaseRequest

type ArgvCommand struct {
	Arguments  []string `json:"arguments"`
	Executable string   `json:"executable"`
	Mode       string   `json:"mode"`
}

type Artifact struct {
	CreatedAt  Timestamp `json:"createdAt"`
	ExpiresAt  Timestamp `json:"expiresAt"`
	Generation int64     `json:"generation"`
	ID         OpaqueID  `json:"id"`
	MediaType  string    `json:"mediaType"`
	Metadata   Metadata  `json:"metadata"`
	Name       string    `json:"name"`
	SandboxID  OpaqueID  `json:"sandboxId"`
	SHA256     string    `json:"sha256"`
	SizeBytes  int64     `json:"sizeBytes"`
}

type ArtifactPage struct {
	Items      []Artifact `json:"items"`
	NextCursor *string    `json:"nextCursor,omitempty"`
}

type BootStage = string

const (
	BootStageRunnerAdmission  BootStage = "runner_admission"
	BootStageArtifactVerify   BootStage = "artifact_verify"
	BootStageWorkspaceAttach  BootStage = "workspace_attach"
	BootStageNetworkSetup     BootStage = "network_setup"
	BootStageComputeLaunch    BootStage = "compute_launch"
	BootStageGuestNegotiation BootStage = "guest_negotiation"
	BootStageReady            BootStage = "ready"
)

type BootStageTiming = contracts.BootStageTiming

type BootStageTimingSummary struct {
	Duration DurationPercentiles `json:"duration"`
	Stage    BootStage           `json:"stage"`
}

type BootTiming = contracts.BootTiming

type BufferedExecRequest struct {
	Command              Command        `json:"command"`
	Cwd                  *WorkspacePath `json:"cwd,omitempty"`
	DeadlineMilliseconds int64          `json:"deadlineMilliseconds"`
	Environment          StringMap      `json:"environment"`
	MaximumOutputBytes   int64          `json:"maximumOutputBytes"`
	StdinBase64          *string        `json:"stdinBase64,omitempty"`
}

type Command struct {
	ShellCommand *ShellCommand `json:"-"`
	ArgvCommand  *ArgvCommand  `json:"-"`
}

type CorrelationID = string

type CreateDirectoryRequest struct {
	Path      WorkspacePath `json:"path"`
	Recursive bool          `json:"recursive"`
}

type CreatePortSessionRequest struct {
	DurationSeconds int64  `json:"durationSeconds"`
	Name            string `json:"name"`
}

type CreateProfileRequest = contracts.CreateProfileRequest

type CreateRunnerPoolRequest = contracts.CreateRunnerPoolRequest

type CreateSandboxRequest = contracts.CreateSandboxRequest

type CreateSnapshotRequest = contracts.CreateSnapshotRequest

type CreateTerminalRequest struct {
	Columns              int            `json:"columns"`
	Command              Command        `json:"command"`
	Cwd                  *WorkspacePath `json:"cwd,omitempty"`
	DeadlineMilliseconds int64          `json:"deadlineMilliseconds"`
	Detachable           bool           `json:"detachable"`
	Environment          StringMap      `json:"environment"`
	Rows                 int            `json:"rows"`
}

type DeploymentTimingSummary = contracts.DeploymentTimingSummary

type DirectoryListing struct {
	Entries []FileStat    `json:"entries"`
	Path    WorkspacePath `json:"path"`
}

type DurationPercentiles = contracts.DurationPercentiles

type ExecCancelled struct {
	Kind   string     `json:"kind"`
	Output ExecOutput `json:"output"`
}

type ExecDeadlineExceeded struct {
	ElapsedMilliseconds int64      `json:"elapsedMilliseconds"`
	Kind                string     `json:"kind"`
	Output              ExecOutput `json:"output"`
}

type ExecExited struct {
	ElapsedMilliseconds int64      `json:"elapsedMilliseconds"`
	ExitCode            int        `json:"exitCode"`
	Kind                string     `json:"kind"`
	Output              ExecOutput `json:"output"`
	Signal              *int       `json:"signal,omitempty"`
}

type ExecInfrastructureFailed struct {
	Kind      string                    `json:"kind"`
	Message   string                    `json:"message"`
	Reason    InfrastructureFailureKind `json:"reason"`
	Retryable bool                      `json:"retryable"`
}

type ExecOutcome struct {
	ExecExited               *ExecExited               `json:"-"`
	ExecSpawnFailed          *ExecSpawnFailed          `json:"-"`
	ExecDeadlineExceeded     *ExecDeadlineExceeded     `json:"-"`
	ExecCancelled            *ExecCancelled            `json:"-"`
	ExecOutputExhausted      *ExecOutputExhausted      `json:"-"`
	ExecInfrastructureFailed *ExecInfrastructureFailed `json:"-"`
}

type ExecOutput struct {
	StderrBase64 string `json:"stderrBase64"`
	StdoutBase64 string `json:"stdoutBase64"`
}

type ExecOutputExhausted struct {
	Kind       string     `json:"kind"`
	LimitBytes int64      `json:"limitBytes"`
	Output     ExecOutput `json:"output"`
}

type ExecSpawnFailed struct {
	Kind    string           `json:"kind"`
	Message string           `json:"message"`
	Reason  SpawnFailureKind `json:"reason"`
}

type ExecStreamFrame struct {
	StreamInputFrame   *StreamInputFrame   `json:"-"`
	StreamOutputFrame  *StreamOutputFrame  `json:"-"`
	StreamCreditFrame  *StreamCreditFrame  `json:"-"`
	StreamSignalFrame  *StreamSignalFrame  `json:"-"`
	StreamCancelFrame  *StreamCancelFrame  `json:"-"`
	StreamOutcomeFrame *StreamOutcomeFrame `json:"-"`
}

type ExecStreamSession struct {
	ExpiresAt    Timestamp    `json:"expiresAt"`
	Generation   int64        `json:"generation"`
	ID           OpaqueID     `json:"id"`
	SandboxID    OpaqueID     `json:"sandboxId"`
	State        SessionState `json:"state"`
	Subprotocol  string       `json:"subprotocol"`
	WebsocketURL string       `json:"websocketUrl"`
}

type ExecTiming = contracts.ExecTiming

type ExecTimingSummary struct {
	Duration DurationPercentiles `json:"duration"`
	Mode     string              `json:"mode"`
	Outcome  string              `json:"outcome"`
}

type ExecutionPolicy = contracts.ExecutionPolicy

type FileExistsResult struct {
	Exists bool          `json:"exists"`
	Path   WorkspacePath `json:"path"`
}

type FileKind = string

const (
	FileKindFile         FileKind = "file"
	FileKindDirectory    FileKind = "directory"
	FileKindSymbolicLink FileKind = "symbolic_link"
)

type FileStat struct {
	Kind       FileKind      `json:"kind"`
	ModifiedAt Timestamp     `json:"modifiedAt"`
	Path       WorkspacePath `json:"path"`
	SizeBytes  int64         `json:"sizeBytes"`
}

type FileWriteResult struct {
	Path      WorkspacePath `json:"path"`
	SHA256    string        `json:"sha256"`
	SizeBytes int64         `json:"sizeBytes"`
}

type GuestLiveness = string

const (
	GuestLivenessUnknown  GuestLiveness = "unknown"
	GuestLivenessStarting GuestLiveness = "starting"
	GuestLivenessReady    GuestLiveness = "ready"
	GuestLivenessLost     GuestLiveness = "lost"
	GuestLivenessStopped  GuestLiveness = "stopped"
)

type HTTPRouteTimingSummary struct {
	Duration    DurationPercentiles `json:"duration"`
	Route       string              `json:"route"`
	StatusClass string              `json:"statusClass"`
}

type InfrastructureFailureKind = string

const (
	InfrastructureFailureKindTransport        InfrastructureFailureKind = "transport"
	InfrastructureFailureKindAdmission        InfrastructureFailureKind = "admission"
	InfrastructureFailureKindGenerationFenced InfrastructureFailureKind = "generation_fenced"
	InfrastructureFailureKindLeaseFenced      InfrastructureFailureKind = "lease_fenced"
	InfrastructureFailureKindGuestAgent       InfrastructureFailureKind = "guest_agent"
	InfrastructureFailureKindExecutionNode    InfrastructureFailureKind = "execution_node"
	InfrastructureFailureKindService          InfrastructureFailureKind = "service"
)

type Instance struct {
	CreatedAt         Timestamp                  `json:"createdAt"`
	Generation        int64                      `json:"generation"`
	GuestHeartbeatAt  *Timestamp                 `json:"guestHeartbeatAt,omitempty"`
	GuestLiveness     GuestLiveness              `json:"guestLiveness"`
	ID                OpaqueID                   `json:"id"`
	ReadyAt           *Timestamp                 `json:"readyAt,omitempty"`
	SandboxID         OpaqueID                   `json:"sandboxId"`
	State             InstanceState              `json:"state"`
	StoppedAt         *Timestamp                 `json:"stoppedAt,omitempty"`
	TerminationReason *InstanceTerminationReason `json:"terminationReason,omitempty"`
	UpdatedAt         Timestamp                  `json:"updatedAt"`
}

type InstanceState = string

const (
	InstanceStateStarting InstanceState = "starting"
	InstanceStateReady    InstanceState = "ready"
	InstanceStateDraining InstanceState = "draining"
	InstanceStateStopping InstanceState = "stopping"
	InstanceStateStopped  InstanceState = "stopped"
	InstanceStateLost     InstanceState = "lost"
	InstanceStateFailed   InstanceState = "failed"
)

type InstanceTerminationReason = string

const (
	InstanceTerminationReasonRequestedDrain     InstanceTerminationReason = "requested_drain"
	InstanceTerminationReasonRequestedStop      InstanceTerminationReason = "requested_stop"
	InstanceTerminationReasonIdleTimeout        InstanceTerminationReason = "idle_timeout"
	InstanceTerminationReasonMaximumDuration    InstanceTerminationReason = "maximum_duration"
	InstanceTerminationReasonGuestShutdown      InstanceTerminationReason = "guest_shutdown"
	InstanceTerminationReasonResourceExhaustion InstanceTerminationReason = "resource_exhaustion"
	InstanceTerminationReasonGuestAgentLost     InstanceTerminationReason = "guest_agent_lost"
	InstanceTerminationReasonRunnerLost         InstanceTerminationReason = "runner_lost"
	InstanceTerminationReasonStartupFailed      InstanceTerminationReason = "startup_failed"
	InstanceTerminationReasonFenced             InstanceTerminationReason = "fenced"
	InstanceTerminationReasonInternalFailure    InstanceTerminationReason = "internal_failure"
)

type Lease = contracts.Lease

type LeaseState = string

const (
	LeaseStateActive   LeaseState = "active"
	LeaseStateReleased LeaseState = "released"
	LeaseStateExpired  LeaseState = "expired"
	LeaseStateFenced   LeaseState = "fenced"
)

type LifecyclePolicy = contracts.LifecyclePolicy

type Metadata = map[string]string

type NetworkDestination = contracts.NetworkDestination

type NetworkPolicy = contracts.NetworkPolicy

type OpaqueID = string

type Operation = contracts.Operation

type OperationKind = string

const (
	OperationKindCreate          OperationKind = "create"
	OperationKindStart           OperationKind = "start"
	OperationKindDrain           OperationKind = "drain"
	OperationKindStop            OperationKind = "stop"
	OperationKindDelete          OperationKind = "delete"
	OperationKindRelocate        OperationKind = "relocate"
	OperationKindSnapshotCreate  OperationKind = "snapshot_create"
	OperationKindSnapshotDelete  OperationKind = "snapshot_delete"
	OperationKindSnapshotRestore OperationKind = "snapshot_restore"
	OperationKindCancelExec      OperationKind = "cancel_exec"
	OperationKindCancelTerminal  OperationKind = "cancel_terminal"
)

type OperationStageTiming = contracts.OperationStageTiming

type OperationState = string

const (
	OperationStatePending   OperationState = "pending"
	OperationStateRunning   OperationState = "running"
	OperationStateSucceeded OperationState = "succeeded"
	OperationStateFailed    OperationState = "failed"
	OperationStateCancelled OperationState = "cancelled"
)

type OperationTiming = contracts.OperationTiming

type OperationTimingSummary struct {
	Execution DurationPercentiles `json:"execution"`
	Kind      OperationKind       `json:"kind"`
	Queue     DurationPercentiles `json:"queue"`
	State     OperationState      `json:"state"`
	Total     DurationPercentiles `json:"total"`
}

type OwnershipRef = string

type PingResult struct {
	Generation int64     `json:"generation"`
	Healthy    bool      `json:"healthy"`
	ObservedAt Timestamp `json:"observedAt"`
	SandboxID  OpaqueID  `json:"sandboxId"`
}

type PortPolicy = contracts.PortPolicy

type PortSession struct {
	CertificateSpkiSha256 *string   `json:"certificateSpkiSha256,omitempty"`
	CreatedAt             Timestamp `json:"createdAt"`
	Endpoint              string    `json:"endpoint"`
	ExpiresAt             Timestamp `json:"expiresAt"`
	Generation            int64     `json:"generation"`
	ID                    OpaqueID  `json:"id"`
	Name                  string    `json:"name"`
	Protocol              string    `json:"protocol"`
	SandboxID             OpaqueID  `json:"sandboxId"`
	State                 string    `json:"state"`
	Transport             string    `json:"transport"`
}

type Problem = contracts.Problem

type ProblemCode = string

const (
	ProblemCodeInvalidRequest                       ProblemCode = "invalid_request"
	ProblemCodeAuthenticationFailed                 ProblemCode = "authentication_failed"
	ProblemCodeAuthorizationFailed                  ProblemCode = "authorization_failed"
	ProblemCodeNotFound                             ProblemCode = "not_found"
	ProblemCodeIdempotencyConflict                  ProblemCode = "idempotency_conflict"
	ProblemCodePreconditionFailed                   ProblemCode = "precondition_failed"
	ProblemCodeStateConflict                        ProblemCode = "state_conflict"
	ProblemCodeWorkspaceMutationConflict            ProblemCode = "workspace_mutation_conflict"
	ProblemCodeGenerationFenced                     ProblemCode = "generation_fenced"
	ProblemCodeLeaseFenced                          ProblemCode = "lease_fenced"
	ProblemCodeProfileUnavailable                   ProblemCode = "profile_unavailable"
	ProblemCodeHomeRunnerUnavailable                ProblemCode = "home_runner_unavailable"
	ProblemCodeSandboxNotStopped                    ProblemCode = "sandbox_not_stopped"
	ProblemCodeWorkspaceRelocationSnapshotsPresent  ProblemCode = "workspace_relocation_snapshots_present"
	ProblemCodeWorkspaceRelocationTargetUnavailable ProblemCode = "workspace_relocation_target_unavailable"
	ProblemCodeQuotaExceeded                        ProblemCode = "quota_exceeded"
	ProblemCodeLimitExceeded                        ProblemCode = "limit_exceeded"
	ProblemCodeGuestUnavailable                     ProblemCode = "guest_unavailable"
	ProblemCodeExecutionNodeUnavailable             ProblemCode = "execution_node_unavailable"
	ProblemCodeDependencyUnavailable                ProblemCode = "dependency_unavailable"
	ProblemCodeInternalError                        ProblemCode = "internal_error"
	ProblemCodeTerminalReplayEvicted                ProblemCode = "terminal_replay_evicted"
	ProblemCodeWaitExpired                          ProblemCode = "wait_expired"
)

type ProblemDetail struct {
	Field  string `json:"field"`
	Reason string `json:"reason"`
}

type Profile = contracts.Profile

type ProfileName = string

type ProfilePage struct {
	Items      []Profile `json:"items"`
	NextCursor *string   `json:"nextCursor,omitempty"`
}

type ProfileRevision struct {
	CreatedAt Timestamp           `json:"createdAt"`
	ID        OpaqueID            `json:"id"`
	Number    int64               `json:"number"`
	Spec      ProfileRevisionSpec `json:"spec"`
}

type ProfileRevisionSpec = contracts.ProfileRevisionSpec

type ProfileState = string

const (
	ProfileStateEnabled  ProfileState = "enabled"
	ProfileStateDisabled ProfileState = "disabled"
)

type RelocateSandboxRequest struct {
	RunnerPool     *ProfileName `json:"runnerPool,omitempty"`
	TargetRunnerID *RunnerID    `json:"targetRunnerId,omitempty"`
}

type RemovePathRequest struct {
	Force     bool          `json:"force"`
	Path      WorkspacePath `json:"path"`
	Recursive bool          `json:"recursive"`
}

type RenewLeaseRequest = contracts.RenewLeaseRequest

type ResourcePolicy = contracts.ResourcePolicy

type RestoreSnapshotRequest = contracts.RestoreSnapshotRequest

type RetentionPolicy = contracts.RetentionPolicy

type ReviseProfileRequest struct {
	Spec ProfileRevisionSpec `json:"spec"`
}

type Runner = contracts.Runner

type RunnerArchitectureList = []string

type RunnerCapabilityList = []string

type RunnerCapacityPolicy = map[string]int64

type RunnerID = string

type RunnerPage = contracts.RunnerPage

type RunnerPool = contracts.RunnerPool

type RunnerPoolPage = contracts.RunnerPoolPage

type RunnerPoolState = string

const (
	RunnerPoolStateReady    RunnerPoolState = "ready"
	RunnerPoolStateDraining RunnerPoolState = "draining"
	RunnerPoolStateOffline  RunnerPoolState = "offline"
)

type Sandbox = contracts.Sandbox

type SandboxDesiredState = string

const (
	SandboxDesiredStateRunning SandboxDesiredState = "running"
	SandboxDesiredStateStopped SandboxDesiredState = "stopped"
	SandboxDesiredStateDeleted SandboxDesiredState = "deleted"
)

type SandboxInspection struct {
	ActiveSessions int64     `json:"activeSessions"`
	Generation     int64     `json:"generation"`
	GuestHealthy   bool      `json:"guestHealthy"`
	ObservedAt     Timestamp `json:"observedAt"`
	SandboxID      OpaqueID  `json:"sandboxId"`
}

type SandboxPage = contracts.SandboxPage

type SandboxState = string

const (
	SandboxStateCreating SandboxState = "creating"
	SandboxStateStopped  SandboxState = "stopped"
	SandboxStateStarting SandboxState = "starting"
	SandboxStateReady    SandboxState = "ready"
	SandboxStateDraining SandboxState = "draining"
	SandboxStateStopping SandboxState = "stopping"
	SandboxStateFailed   SandboxState = "failed"
	SandboxStateDeleting SandboxState = "deleting"
	SandboxStateDeleted  SandboxState = "deleted"
)

type SandboxTiming = contracts.SandboxTiming

type SessionState = string

const (
	SessionStateOpen     SessionState = "open"
	SessionStateDetached SessionState = "detached"
	SessionStateClosing  SessionState = "closing"
	SessionStateClosed   SessionState = "closed"
)

type ShellCommand struct {
	Command string `json:"command"`
	Mode    string `json:"mode"`
}

type Snapshot = contracts.Snapshot

type SnapshotPage = contracts.SnapshotPage

type SpawnFailureKind = string

const (
	SpawnFailureKindNotFound            SpawnFailureKind = "not_found"
	SpawnFailureKindPermissionDenied    SpawnFailureKind = "permission_denied"
	SpawnFailureKindInvalidCwd          SpawnFailureKind = "invalid_cwd"
	SpawnFailureKindMalformedExecutable SpawnFailureKind = "malformed_executable"
)

type StreamCancelFrame struct {
	Sequence int64  `json:"sequence"`
	Type     string `json:"type"`
}

type StreamCreditFrame struct {
	Bytes    int64  `json:"bytes"`
	Sequence int64  `json:"sequence"`
	Type     string `json:"type"`
}

type StreamInputFrame struct {
	DataBase64 string `json:"dataBase64"`
	EndOfInput bool   `json:"endOfInput"`
	Sequence   int64  `json:"sequence"`
	Type       string `json:"type"`
}

type StreamOutcomeFrame struct {
	Outcome  ExecOutcome `json:"outcome"`
	Sequence int64       `json:"sequence"`
	Type     string      `json:"type"`
}

type StreamOutputFrame struct {
	DataBase64 string `json:"dataBase64"`
	Sequence   int64  `json:"sequence"`
	Stream     string `json:"stream"`
	Type       string `json:"type"`
}

type StreamSignalFrame struct {
	Sequence int64  `json:"sequence"`
	Signal   int    `json:"signal"`
	Type     string `json:"type"`
}

type StreamingExecRequest struct {
	Command              Command        `json:"command"`
	Cwd                  *WorkspacePath `json:"cwd,omitempty"`
	DeadlineMilliseconds int64          `json:"deadlineMilliseconds"`
	Environment          StringMap      `json:"environment"`
	MaximumOutputBytes   int64          `json:"maximumOutputBytes"`
	WindowBytes          int64          `json:"windowBytes"`
}

type StringMap = map[string]string

type TerminalAttachedFrame struct {
	NextClientSequence *int64 `json:"nextClientSequence,omitempty"`
	Type               string `json:"type"`
}

type TerminalFrame struct {
	TerminalAttachedFrame *TerminalAttachedFrame `json:"-"`
	TerminalInputFrame    *TerminalInputFrame    `json:"-"`
	TerminalOutputFrame   *TerminalOutputFrame   `json:"-"`
	TerminalResizeFrame   *TerminalResizeFrame   `json:"-"`
	StreamCreditFrame     *StreamCreditFrame     `json:"-"`
	StreamCancelFrame     *StreamCancelFrame     `json:"-"`
	StreamOutcomeFrame    *StreamOutcomeFrame    `json:"-"`
}

type TerminalInputFrame struct {
	DataBase64 string `json:"dataBase64"`
	Sequence   int64  `json:"sequence"`
	Type       string `json:"type"`
}

type TerminalOutputFrame struct {
	DataBase64 string `json:"dataBase64"`
	Sequence   int64  `json:"sequence"`
	Type       string `json:"type"`
}

type TerminalResizeFrame struct {
	Columns  int    `json:"columns"`
	Rows     int    `json:"rows"`
	Sequence int64  `json:"sequence"`
	Type     string `json:"type"`
}

type TerminalSession struct {
	ExpiresAt          Timestamp    `json:"expiresAt"`
	Generation         int64        `json:"generation"`
	ID                 OpaqueID     `json:"id"`
	NextClientSequence int64        `json:"nextClientSequence"`
	SandboxID          OpaqueID     `json:"sandboxId"`
	State              SessionState `json:"state"`
	StreamWindowBytes  int64        `json:"streamWindowBytes"`
	Subprotocol        string       `json:"subprotocol"`
	WebsocketURL       string       `json:"websocketUrl"`
}

type Timestamp = time.Time

type TouchResult struct {
	Generation     int64     `json:"generation"`
	LastActivityAt Timestamp `json:"lastActivityAt"`
	SandboxID      OpaqueID  `json:"sandboxId"`
}

type UpdateRunnerPoolRequest struct {
	Architectures  RunnerArchitectureList `json:"architectures,omitempty"`
	Capabilities   RunnerCapabilityList   `json:"capabilities,omitempty"`
	CapacityPolicy RunnerCapacityPolicy   `json:"capacityPolicy,omitempty"`
	State          *RunnerPoolState       `json:"state,omitempty"`
}

type UpdateSandboxMetadataRequest struct {
	Metadata Metadata `json:"metadata"`
}

type UploadArtifactRequest struct {
	Content   string   `json:"content"`
	MediaType string   `json:"mediaType"`
	Metadata  Metadata `json:"metadata"`
	Name      string   `json:"name"`
	SHA256    string   `json:"sha256"`
}

type WaitSandboxRequest struct {
	DeadlineMilliseconds int64          `json:"deadlineMilliseconds"`
	States               []SandboxState `json:"states"`
}

type Workspace struct {
	CreatedAt  Timestamp `json:"createdAt"`
	Generation int64     `json:"generation"`
	ID         OpaqueID  `json:"id"`
	SizeBytes  int64     `json:"sizeBytes"`
	State      string    `json:"state"`
	UpdatedAt  Timestamp `json:"updatedAt"`
}

type WorkspacePath = string
