// Code generated by secondbox-sdkgen. DO NOT EDIT.

package secondboxclient

import "time"

type AcquireLeaseRequest struct {
	DurationSeconds int64 `json:"durationSeconds"`
}

type ArgvCommand struct {
	Arguments  []string `json:"arguments"`
	Executable string   `json:"executable"`
	Mode       string   `json:"mode"`
}

type Artifact struct {
	CreatedAt  Timestamp `json:"createdAt"`
	ExpiresAt  Timestamp `json:"expiresAt"`
	Generation int64     `json:"generation"`
	ID         OpaqueID  `json:"id"`
	MediaType  string    `json:"mediaType"`
	Metadata   Metadata  `json:"metadata"`
	Name       string    `json:"name"`
	SandboxID  OpaqueID  `json:"sandboxId"`
	SHA256     string    `json:"sha256"`
	SizeBytes  int64     `json:"sizeBytes"`
}

type ArtifactPage struct {
	Items      []Artifact `json:"items"`
	NextCursor *string    `json:"nextCursor,omitempty"`
}

type BootStage = string

const (
	BootStageRunnerAdmission  BootStage = "runner_admission"
	BootStageArtifactVerify   BootStage = "artifact_verify"
	BootStageWorkspaceAttach  BootStage = "workspace_attach"
	BootStageNetworkSetup     BootStage = "network_setup"
	BootStageComputeLaunch    BootStage = "compute_launch"
	BootStageGuestNegotiation BootStage = "guest_negotiation"
	BootStageReady            BootStage = "ready"
)

type BootStageTiming struct {
	CumulativeMilliseconds float64   `json:"cumulativeMilliseconds"`
	ElapsedMilliseconds    float64   `json:"elapsedMilliseconds"`
	ObservedAt             Timestamp `json:"observedAt"`
	ReceivedAt             Timestamp `json:"receivedAt"`
	Stage                  BootStage `json:"stage"`
}

type BootStageTimingSummary struct {
	Duration DurationPercentiles `json:"duration"`
	Stage    BootStage           `json:"stage"`
}

type BootTiming struct {
	Completed            bool              `json:"completed"`
	DurationMilliseconds float64           `json:"durationMilliseconds"`
	Generation           int64             `json:"generation"`
	Stages               []BootStageTiming `json:"stages"`
}

type BufferedExecRequest struct {
	Command              Command        `json:"command"`
	Cwd                  *WorkspacePath `json:"cwd,omitempty"`
	DeadlineMilliseconds int64          `json:"deadlineMilliseconds"`
	Environment          StringMap      `json:"environment"`
	MaximumOutputBytes   int64          `json:"maximumOutputBytes"`
	StdinBase64          *string        `json:"stdinBase64,omitempty"`
}

type Command struct {
	ShellCommand *ShellCommand `json:"-"`
	ArgvCommand  *ArgvCommand  `json:"-"`
}

type CorrelationID = string

type CreateDirectoryRequest struct {
	Path      WorkspacePath `json:"path"`
	Recursive bool          `json:"recursive"`
}

type CreatePortSessionRequest struct {
	DurationSeconds int64  `json:"durationSeconds"`
	Name            string `json:"name"`
}

type CreateProfileRequest struct {
	Name ProfileName         `json:"name"`
	Spec ProfileRevisionSpec `json:"spec"`
}

type CreateRunnerPoolRequest struct {
	Architectures  RunnerArchitectureList `json:"architectures"`
	Capabilities   RunnerCapabilityList   `json:"capabilities"`
	CapacityPolicy RunnerCapacityPolicy   `json:"capacityPolicy"`
	Name           ProfileName            `json:"name"`
	State          RunnerPoolState        `json:"state"`
}

type CreateSandboxRequest struct {
	Metadata         Metadata    `json:"metadata"`
	Profile          ProfileName `json:"profile"`
	SourceSnapshotID *OpaqueID   `json:"sourceSnapshotId,omitempty"`
}

type CreateSnapshotRequest struct {
	Metadata Metadata `json:"metadata"`
	Name     string   `json:"name"`
}

type CreateTerminalRequest struct {
	Columns              int            `json:"columns"`
	Command              Command        `json:"command"`
	Cwd                  *WorkspacePath `json:"cwd,omitempty"`
	DeadlineMilliseconds int64          `json:"deadlineMilliseconds"`
	Detachable           bool           `json:"detachable"`
	Environment          StringMap      `json:"environment"`
	Rows                 int            `json:"rows"`
}

type DeploymentTimingSummary struct {
	API               DurationPercentiles      `json:"api"`
	APISeries         []HTTPRouteTimingSummary `json:"apiSeries"`
	Boot              DurationPercentiles      `json:"boot"`
	BootStages        []BootStageTimingSummary `json:"bootStages"`
	DominantBootStage *BootStageTimingSummary  `json:"dominantBootStage,omitempty"`
	Exec              DurationPercentiles      `json:"exec"`
	ExecSeries        []ExecTimingSummary      `json:"execSeries"`
	ObservedAt        Timestamp                `json:"observedAt"`
	Operations        []OperationTimingSummary `json:"operations"`
	WindowSeconds     int64                    `json:"windowSeconds"`
}

type DirectoryListing struct {
	Entries []FileStat    `json:"entries"`
	Path    WorkspacePath `json:"path"`
}

type DurationPercentiles struct {
	Count           int64    `json:"count"`
	P50Milliseconds *float64 `json:"p50Milliseconds,omitempty"`
	P95Milliseconds *float64 `json:"p95Milliseconds,omitempty"`
	P99Milliseconds *float64 `json:"p99Milliseconds,omitempty"`
}

type ExecCancelled struct {
	Kind   string     `json:"kind"`
	Output ExecOutput `json:"output"`
}

type ExecDeadlineExceeded struct {
	ElapsedMilliseconds int64      `json:"elapsedMilliseconds"`
	Kind                string     `json:"kind"`
	Output              ExecOutput `json:"output"`
}

type ExecExited struct {
	ElapsedMilliseconds int64      `json:"elapsedMilliseconds"`
	ExitCode            int        `json:"exitCode"`
	Kind                string     `json:"kind"`
	Output              ExecOutput `json:"output"`
	Signal              *int       `json:"signal,omitempty"`
}

type ExecInfrastructureFailed struct {
	Kind      string                    `json:"kind"`
	Message   string                    `json:"message"`
	Reason    InfrastructureFailureKind `json:"reason"`
	Retryable bool                      `json:"retryable"`
}

type ExecOutcome struct {
	ExecExited               *ExecExited               `json:"-"`
	ExecSpawnFailed          *ExecSpawnFailed          `json:"-"`
	ExecDeadlineExceeded     *ExecDeadlineExceeded     `json:"-"`
	ExecCancelled            *ExecCancelled            `json:"-"`
	ExecOutputExhausted      *ExecOutputExhausted      `json:"-"`
	ExecInfrastructureFailed *ExecInfrastructureFailed `json:"-"`
}

type ExecOutput struct {
	StderrBase64 string `json:"stderrBase64"`
	StdoutBase64 string `json:"stdoutBase64"`
}

type ExecOutputExhausted struct {
	Kind       string     `json:"kind"`
	LimitBytes int64      `json:"limitBytes"`
	Output     ExecOutput `json:"output"`
}

type ExecSpawnFailed struct {
	Kind    string           `json:"kind"`
	Message string           `json:"message"`
	Reason  SpawnFailureKind `json:"reason"`
}

type ExecStreamFrame struct {
	StreamInputFrame   *StreamInputFrame   `json:"-"`
	StreamOutputFrame  *StreamOutputFrame  `json:"-"`
	StreamCreditFrame  *StreamCreditFrame  `json:"-"`
	StreamSignalFrame  *StreamSignalFrame  `json:"-"`
	StreamCancelFrame  *StreamCancelFrame  `json:"-"`
	StreamOutcomeFrame *StreamOutcomeFrame `json:"-"`
}

type ExecStreamSession struct {
	ExpiresAt    Timestamp    `json:"expiresAt"`
	Generation   int64        `json:"generation"`
	ID           OpaqueID     `json:"id"`
	SandboxID    OpaqueID     `json:"sandboxId"`
	State        SessionState `json:"state"`
	Subprotocol  string       `json:"subprotocol"`
	WebsocketURL string       `json:"websocketUrl"`
}

type ExecTiming struct {
	CompletedAt         Timestamp `json:"completedAt"`
	CreatedAt           Timestamp `json:"createdAt"`
	ElapsedMilliseconds int64     `json:"elapsedMilliseconds"`
	Mode                string    `json:"mode"`
	Outcome             string    `json:"outcome"`
	SessionID           OpaqueID  `json:"sessionId"`
}

type ExecTimingSummary struct {
	Duration DurationPercentiles `json:"duration"`
	Mode     string              `json:"mode"`
	Outcome  string              `json:"outcome"`
}

type ExecutionPolicy struct {
	DataPlaneTransport          string `json:"dataPlaneTransport"`
	MaximumBufferedOutputBytes  int64  `json:"maximumBufferedOutputBytes"`
	MaximumDeadlineMilliseconds int64  `json:"maximumDeadlineMilliseconds"`
	MaximumTransferBytes        int64  `json:"maximumTransferBytes"`
	StreamWindowBytes           int64  `json:"streamWindowBytes"`
	TerminalDetachSeconds       int64  `json:"terminalDetachSeconds"`
}

type FileExistsResult struct {
	Exists bool          `json:"exists"`
	Path   WorkspacePath `json:"path"`
}

type FileKind = string

const (
	FileKindFile         FileKind = "file"
	FileKindDirectory    FileKind = "directory"
	FileKindSymbolicLink FileKind = "symbolic_link"
)

type FileStat struct {
	Kind       FileKind      `json:"kind"`
	ModifiedAt Timestamp     `json:"modifiedAt"`
	Path       WorkspacePath `json:"path"`
	SizeBytes  int64         `json:"sizeBytes"`
}

type FileWriteResult struct {
	Path      WorkspacePath `json:"path"`
	SHA256    string        `json:"sha256"`
	SizeBytes int64         `json:"sizeBytes"`
}

type GuestLiveness = string

const (
	GuestLivenessUnknown  GuestLiveness = "unknown"
	GuestLivenessStarting GuestLiveness = "starting"
	GuestLivenessReady    GuestLiveness = "ready"
	GuestLivenessLost     GuestLiveness = "lost"
	GuestLivenessStopped  GuestLiveness = "stopped"
)

type HTTPRouteTimingSummary struct {
	Duration    DurationPercentiles `json:"duration"`
	Route       string              `json:"route"`
	StatusClass string              `json:"statusClass"`
}

type InfrastructureFailureKind = string

const (
	InfrastructureFailureKindTransport        InfrastructureFailureKind = "transport"
	InfrastructureFailureKindAdmission        InfrastructureFailureKind = "admission"
	InfrastructureFailureKindGenerationFenced InfrastructureFailureKind = "generation_fenced"
	InfrastructureFailureKindLeaseFenced      InfrastructureFailureKind = "lease_fenced"
	InfrastructureFailureKindGuestAgent       InfrastructureFailureKind = "guest_agent"
	InfrastructureFailureKindExecutionNode    InfrastructureFailureKind = "execution_node"
	InfrastructureFailureKindService          InfrastructureFailureKind = "service"
)

type Instance struct {
	CreatedAt         Timestamp                  `json:"createdAt"`
	Generation        int64                      `json:"generation"`
	GuestHeartbeatAt  *Timestamp                 `json:"guestHeartbeatAt,omitempty"`
	GuestLiveness     GuestLiveness              `json:"guestLiveness"`
	ID                OpaqueID                   `json:"id"`
	ReadyAt           *Timestamp                 `json:"readyAt,omitempty"`
	SandboxID         OpaqueID                   `json:"sandboxId"`
	State             InstanceState              `json:"state"`
	StoppedAt         *Timestamp                 `json:"stoppedAt,omitempty"`
	TerminationReason *InstanceTerminationReason `json:"terminationReason,omitempty"`
	UpdatedAt         Timestamp                  `json:"updatedAt"`
}

type InstanceState = string

const (
	InstanceStateStarting InstanceState = "starting"
	InstanceStateReady    InstanceState = "ready"
	InstanceStateDraining InstanceState = "draining"
	InstanceStateStopping InstanceState = "stopping"
	InstanceStateStopped  InstanceState = "stopped"
	InstanceStateLost     InstanceState = "lost"
	InstanceStateFailed   InstanceState = "failed"
)

type InstanceTerminationReason = string

const (
	InstanceTerminationReasonRequestedDrain     InstanceTerminationReason = "requested_drain"
	InstanceTerminationReasonRequestedStop      InstanceTerminationReason = "requested_stop"
	InstanceTerminationReasonIdleTimeout        InstanceTerminationReason = "idle_timeout"
	InstanceTerminationReasonMaximumDuration    InstanceTerminationReason = "maximum_duration"
	InstanceTerminationReasonGuestShutdown      InstanceTerminationReason = "guest_shutdown"
	InstanceTerminationReasonResourceExhaustion InstanceTerminationReason = "resource_exhaustion"
	InstanceTerminationReasonGuestAgentLost     InstanceTerminationReason = "guest_agent_lost"
	InstanceTerminationReasonRunnerLost         InstanceTerminationReason = "runner_lost"
	InstanceTerminationReasonStartupFailed      InstanceTerminationReason = "startup_failed"
	InstanceTerminationReasonFenced             InstanceTerminationReason = "fenced"
	InstanceTerminationReasonInternalFailure    InstanceTerminationReason = "internal_failure"
)

type Lease struct {
	CreatedAt  Timestamp  `json:"createdAt"`
	ExpiresAt  Timestamp  `json:"expiresAt"`
	Generation int64      `json:"generation"`
	ID         OpaqueID   `json:"id"`
	SandboxID  OpaqueID   `json:"sandboxId"`
	State      LeaseState `json:"state"`
	UpdatedAt  Timestamp  `json:"updatedAt"`
}

type LeaseState = string

const (
	LeaseStateActive   LeaseState = "active"
	LeaseStateReleased LeaseState = "released"
	LeaseStateExpired  LeaseState = "expired"
	LeaseStateFenced   LeaseState = "fenced"
)

type LifecyclePolicy struct {
	DrainGraceSeconds      int64  `json:"drainGraceSeconds"`
	IdleSeconds            int64  `json:"idleSeconds"`
	InitialState           string `json:"initialState"`
	LeaseSeconds           int64  `json:"leaseSeconds"`
	MaximumDurationSeconds int64  `json:"maximumDurationSeconds"`
}

type Metadata = map[string]string

type NetworkDestination struct {
	CIDR     *string `json:"cidr,omitempty"`
	Domain   *string `json:"domain,omitempty"`
	Port     int64   `json:"port"`
	Protocol string  `json:"protocol"`
}

type NetworkPolicy struct {
	Destinations []NetworkDestination `json:"destinations"`
	Mode         string               `json:"mode"`
}

type OpaqueID = string

type Operation struct {
	CompletedAt *Timestamp     `json:"completedAt,omitempty"`
	CreatedAt   Timestamp      `json:"createdAt"`
	Error       *Problem       `json:"error,omitempty"`
	ID          OpaqueID       `json:"id"`
	Kind        OperationKind  `json:"kind"`
	RequestID   CorrelationID  `json:"requestId"`
	Sandbox     *Sandbox       `json:"sandbox,omitempty"`
	SandboxID   OpaqueID       `json:"sandboxId"`
	Snapshot    *Snapshot      `json:"snapshot,omitempty"`
	StartedAt   *Timestamp     `json:"startedAt,omitempty"`
	State       OperationState `json:"state"`
	UpdatedAt   Timestamp      `json:"updatedAt"`
}

type OperationKind = string

const (
	OperationKindCreate          OperationKind = "create"
	OperationKindStart           OperationKind = "start"
	OperationKindDrain           OperationKind = "drain"
	OperationKindStop            OperationKind = "stop"
	OperationKindDelete          OperationKind = "delete"
	OperationKindSnapshotCreate  OperationKind = "snapshot_create"
	OperationKindSnapshotDelete  OperationKind = "snapshot_delete"
	OperationKindSnapshotRestore OperationKind = "snapshot_restore"
	OperationKindCancelExec      OperationKind = "cancel_exec"
	OperationKindCancelTerminal  OperationKind = "cancel_terminal"
)

type OperationStageTiming struct {
	CumulativeMilliseconds float64   `json:"cumulativeMilliseconds"`
	ElapsedMilliseconds    float64   `json:"elapsedMilliseconds"`
	ObservedAt             Timestamp `json:"observedAt"`
	Stage                  string    `json:"stage"`
}

type OperationState = string

const (
	OperationStatePending   OperationState = "pending"
	OperationStateRunning   OperationState = "running"
	OperationStateSucceeded OperationState = "succeeded"
	OperationStateFailed    OperationState = "failed"
	OperationStateCancelled OperationState = "cancelled"
)

type OperationTiming struct {
	Boots                 []BootTiming           `json:"boots"`
	CompletedAt           *Timestamp             `json:"completedAt,omitempty"`
	CreatedAt             Timestamp              `json:"createdAt"`
	ExecutionMilliseconds *int64                 `json:"executionMilliseconds,omitempty"`
	Kind                  OperationKind          `json:"kind"`
	OperationID           OpaqueID               `json:"operationId"`
	Orchestration         []OperationStageTiming `json:"orchestration"`
	QueueMilliseconds     *int64                 `json:"queueMilliseconds,omitempty"`
	SandboxID             OpaqueID               `json:"sandboxId"`
	StartedAt             *Timestamp             `json:"startedAt,omitempty"`
	State                 OperationState         `json:"state"`
	TotalMilliseconds     *int64                 `json:"totalMilliseconds,omitempty"`
}

type OperationTimingSummary struct {
	Execution DurationPercentiles `json:"execution"`
	Kind      OperationKind       `json:"kind"`
	Queue     DurationPercentiles `json:"queue"`
	State     OperationState      `json:"state"`
	Total     DurationPercentiles `json:"total"`
}

type OwnershipRef = string

type PingResult struct {
	Generation int64     `json:"generation"`
	Healthy    bool      `json:"healthy"`
	ObservedAt Timestamp `json:"observedAt"`
	SandboxID  OpaqueID  `json:"sandboxId"`
}

type PortPolicy struct {
	MaximumSessionSeconds int64  `json:"maximumSessionSeconds"`
	MaximumSessions       int64  `json:"maximumSessions"`
	Name                  string `json:"name"`
	Port                  int64  `json:"port"`
	Protocol              string `json:"protocol"`
}

type PortSession struct {
	CertificateSpkiSha256 *string   `json:"certificateSpkiSha256,omitempty"`
	CreatedAt             Timestamp `json:"createdAt"`
	Endpoint              string    `json:"endpoint"`
	ExpiresAt             Timestamp `json:"expiresAt"`
	Generation            int64     `json:"generation"`
	ID                    OpaqueID  `json:"id"`
	Name                  string    `json:"name"`
	Protocol              string    `json:"protocol"`
	SandboxID             OpaqueID  `json:"sandboxId"`
	State                 string    `json:"state"`
	Transport             string    `json:"transport"`
}

type Problem struct {
	Code                   ProblemCode     `json:"code"`
	Details                []ProblemDetail `json:"details,omitempty"`
	RequestID              CorrelationID   `json:"requestId"`
	RetryAfterMilliseconds *int64          `json:"retryAfterMilliseconds,omitempty"`
	Retryable              bool            `json:"retryable"`
	Status                 int             `json:"status"`
	Title                  string          `json:"title"`
	Type                   string          `json:"type"`
}

type ProblemCode = string

const (
	ProblemCodeInvalidRequest            ProblemCode = "invalid_request"
	ProblemCodeAuthenticationFailed      ProblemCode = "authentication_failed"
	ProblemCodeAuthorizationFailed       ProblemCode = "authorization_failed"
	ProblemCodeNotFound                  ProblemCode = "not_found"
	ProblemCodeIdempotencyConflict       ProblemCode = "idempotency_conflict"
	ProblemCodePreconditionFailed        ProblemCode = "precondition_failed"
	ProblemCodeStateConflict             ProblemCode = "state_conflict"
	ProblemCodeWorkspaceMutationConflict ProblemCode = "workspace_mutation_conflict"
	ProblemCodeGenerationFenced          ProblemCode = "generation_fenced"
	ProblemCodeLeaseFenced               ProblemCode = "lease_fenced"
	ProblemCodeProfileUnavailable        ProblemCode = "profile_unavailable"
	ProblemCodeHomeRunnerUnavailable     ProblemCode = "home_runner_unavailable"
	ProblemCodeQuotaExceeded             ProblemCode = "quota_exceeded"
	ProblemCodeLimitExceeded             ProblemCode = "limit_exceeded"
	ProblemCodeGuestUnavailable          ProblemCode = "guest_unavailable"
	ProblemCodeExecutionNodeUnavailable  ProblemCode = "execution_node_unavailable"
	ProblemCodeDependencyUnavailable     ProblemCode = "dependency_unavailable"
	ProblemCodeInternalError             ProblemCode = "internal_error"
	ProblemCodeWaitExpired               ProblemCode = "wait_expired"
)

type ProblemDetail struct {
	Field  string `json:"field"`
	Reason string `json:"reason"`
}

type Profile struct {
	CreatedAt       Timestamp       `json:"createdAt"`
	CurrentRevision ProfileRevision `json:"currentRevision"`
	Name            ProfileName     `json:"name"`
	Revision        int64           `json:"revision"`
	State           ProfileState    `json:"state"`
	UpdatedAt       Timestamp       `json:"updatedAt"`
}

type ProfileName = string

type ProfilePage struct {
	Items      []Profile `json:"items"`
	NextCursor *string   `json:"nextCursor,omitempty"`
}

type ProfileRevision struct {
	CreatedAt Timestamp           `json:"createdAt"`
	ID        OpaqueID            `json:"id"`
	Number    int64               `json:"number"`
	Spec      ProfileRevisionSpec `json:"spec"`
}

type ProfileRevisionSpec struct {
	Architecture          string          `json:"architecture"`
	Execution             ExecutionPolicy `json:"execution"`
	Lifecycle             LifecyclePolicy `json:"lifecycle"`
	Network               NetworkPolicy   `json:"network"`
	Pool                  string          `json:"pool"`
	Ports                 []PortPolicy    `json:"ports"`
	Resources             ResourcePolicy  `json:"resources"`
	Retention             RetentionPolicy `json:"retention"`
	RuntimeBundleDigest   string          `json:"runtimeBundleDigest"`
	ToolchainBundleDigest string          `json:"toolchainBundleDigest"`
}

type ProfileState = string

const (
	ProfileStateEnabled  ProfileState = "enabled"
	ProfileStateDisabled ProfileState = "disabled"
)

type RemovePathRequest struct {
	Force     bool          `json:"force"`
	Path      WorkspacePath `json:"path"`
	Recursive bool          `json:"recursive"`
}

type RenewLeaseRequest struct {
	DurationSeconds int64 `json:"durationSeconds"`
}

type ResourcePolicy struct {
	ConcurrentOperations int64 `json:"concurrentOperations"`
	CPUMillis            int64 `json:"cpuMillis"`
	MemoryBytes          int64 `json:"memoryBytes"`
	ProcessLimit         int64 `json:"processLimit"`
	WorkspaceBytes       int64 `json:"workspaceBytes"`
}

type RestoreSnapshotRequest struct {
	SnapshotID OpaqueID `json:"snapshotId"`
}

type RetentionPolicy struct {
	ArtifactRetentionSeconds int64 `json:"artifactRetentionSeconds"`
	SnapshotLimit            int64 `json:"snapshotLimit"`
	SnapshotRetentionSeconds int64 `json:"snapshotRetentionSeconds"`
}

type ReviseProfileRequest struct {
	Spec ProfileRevisionSpec `json:"spec"`
}

type Runner struct {
	Architectures               []string         `json:"architectures"`
	Capabilities                []string         `json:"capabilities"`
	Capacity                    map[string]int64 `json:"capacity"`
	CreatedAt                   Timestamp        `json:"createdAt"`
	CredentialState             string           `json:"credentialState"`
	ID                          RunnerID         `json:"id"`
	LastSeenAt                  *Timestamp       `json:"lastSeenAt,omitempty"`
	Name                        string           `json:"name"`
	PoolName                    ProfileName      `json:"poolName"`
	ProtocolVersions            []string         `json:"protocolVersions"`
	Revision                    int64            `json:"revision"`
	SandboxStartP95Milliseconds int64            `json:"sandboxStartP95Milliseconds"`
	SandboxStartSampleCount     int64            `json:"sandboxStartSampleCount"`
	State                       string           `json:"state"`
	UpdatedAt                   Timestamp        `json:"updatedAt"`
}

type RunnerArchitectureList = []string

type RunnerCapabilityList = []string

type RunnerCapacityPolicy = map[string]int64

type RunnerID = string

type RunnerPage struct {
	Items      []Runner `json:"items"`
	NextCursor *string  `json:"nextCursor,omitempty"`
}

type RunnerPool struct {
	Architectures    RunnerArchitectureList `json:"architectures"`
	Capabilities     RunnerCapabilityList   `json:"capabilities"`
	CapacityPolicy   RunnerCapacityPolicy   `json:"capacityPolicy"`
	CreatedAt        Timestamp              `json:"createdAt"`
	Name             ProfileName            `json:"name"`
	ReadyRunnerCount int64                  `json:"readyRunnerCount"`
	Revision         int64                  `json:"revision"`
	State            RunnerPoolState        `json:"state"`
	UpdatedAt        Timestamp              `json:"updatedAt"`
}

type RunnerPoolPage struct {
	Items      []RunnerPool `json:"items"`
	NextCursor *string      `json:"nextCursor,omitempty"`
}

type RunnerPoolState = string

const (
	RunnerPoolStateReady    RunnerPoolState = "ready"
	RunnerPoolStateDraining RunnerPoolState = "draining"
	RunnerPoolStateOffline  RunnerPoolState = "offline"
)

type Sandbox struct {
	CreatedAt         Timestamp           `json:"createdAt"`
	DeletedAt         *Timestamp          `json:"deletedAt,omitempty"`
	DesiredState      SandboxDesiredState `json:"desiredState"`
	Generation        int64               `json:"generation"`
	ID                OpaqueID            `json:"id"`
	Instance          *Instance           `json:"instance,omitempty"`
	LastActivityAt    *Timestamp          `json:"lastActivityAt,omitempty"`
	Metadata          Metadata            `json:"metadata"`
	Profile           ProfileName         `json:"profile"`
	ProfileRevisionID OpaqueID            `json:"profileRevisionId"`
	Revision          int64               `json:"revision"`
	State             SandboxState        `json:"state"`
	UpdatedAt         Timestamp           `json:"updatedAt"`
	Workspace         Workspace           `json:"workspace"`
}

type SandboxDesiredState = string

const (
	SandboxDesiredStateRunning SandboxDesiredState = "running"
	SandboxDesiredStateStopped SandboxDesiredState = "stopped"
	SandboxDesiredStateDeleted SandboxDesiredState = "deleted"
)

type SandboxInspection struct {
	ActiveSessions int64     `json:"activeSessions"`
	Generation     int64     `json:"generation"`
	GuestHealthy   bool      `json:"guestHealthy"`
	ObservedAt     Timestamp `json:"observedAt"`
	SandboxID      OpaqueID  `json:"sandboxId"`
}

type SandboxPage struct {
	Items      []Sandbox `json:"items"`
	NextCursor *string   `json:"nextCursor,omitempty"`
}

type SandboxState = string

const (
	SandboxStateCreating SandboxState = "creating"
	SandboxStateStopped  SandboxState = "stopped"
	SandboxStateStarting SandboxState = "starting"
	SandboxStateReady    SandboxState = "ready"
	SandboxStateDraining SandboxState = "draining"
	SandboxStateStopping SandboxState = "stopping"
	SandboxStateFailed   SandboxState = "failed"
	SandboxStateDeleting SandboxState = "deleting"
	SandboxStateDeleted  SandboxState = "deleted"
)

type SandboxTiming struct {
	Execs      []ExecTiming      `json:"execs"`
	Operations []OperationTiming `json:"operations"`
	SandboxID  OpaqueID          `json:"sandboxId"`
}

type SessionState = string

const (
	SessionStateOpen     SessionState = "open"
	SessionStateDetached SessionState = "detached"
	SessionStateClosing  SessionState = "closing"
	SessionStateClosed   SessionState = "closed"
)

type ShellCommand struct {
	Command string `json:"command"`
	Mode    string `json:"mode"`
}

type Snapshot struct {
	CreatedAt  Timestamp  `json:"createdAt"`
	ExpiresAt  *Timestamp `json:"expiresAt,omitempty"`
	Generation int64      `json:"generation"`
	ID         OpaqueID   `json:"id"`
	Metadata   Metadata   `json:"metadata"`
	Name       string     `json:"name"`
	SandboxID  OpaqueID   `json:"sandboxId"`
	SizeBytes  int64      `json:"sizeBytes"`
	State      string     `json:"state"`
}

type SnapshotPage struct {
	Items      []Snapshot `json:"items"`
	NextCursor *string    `json:"nextCursor,omitempty"`
}

type SpawnFailureKind = string

const (
	SpawnFailureKindNotFound            SpawnFailureKind = "not_found"
	SpawnFailureKindPermissionDenied    SpawnFailureKind = "permission_denied"
	SpawnFailureKindInvalidCwd          SpawnFailureKind = "invalid_cwd"
	SpawnFailureKindMalformedExecutable SpawnFailureKind = "malformed_executable"
)

type StreamCancelFrame struct {
	Sequence int64  `json:"sequence"`
	Type     string `json:"type"`
}

type StreamCreditFrame struct {
	Bytes    int64  `json:"bytes"`
	Sequence int64  `json:"sequence"`
	Type     string `json:"type"`
}

type StreamInputFrame struct {
	DataBase64 string `json:"dataBase64"`
	EndOfInput bool   `json:"endOfInput"`
	Sequence   int64  `json:"sequence"`
	Type       string `json:"type"`
}

type StreamOutcomeFrame struct {
	Outcome  ExecOutcome `json:"outcome"`
	Sequence int64       `json:"sequence"`
	Type     string      `json:"type"`
}

type StreamOutputFrame struct {
	DataBase64 string `json:"dataBase64"`
	Sequence   int64  `json:"sequence"`
	Stream     string `json:"stream"`
	Type       string `json:"type"`
}

type StreamSignalFrame struct {
	Sequence int64  `json:"sequence"`
	Signal   int    `json:"signal"`
	Type     string `json:"type"`
}

type StreamingExecRequest struct {
	Command              Command        `json:"command"`
	Cwd                  *WorkspacePath `json:"cwd,omitempty"`
	DeadlineMilliseconds int64          `json:"deadlineMilliseconds"`
	Environment          StringMap      `json:"environment"`
	MaximumOutputBytes   int64          `json:"maximumOutputBytes"`
	WindowBytes          int64          `json:"windowBytes"`
}

type StringMap = map[string]string

type TerminalFrame struct {
	TerminalInputFrame  *TerminalInputFrame  `json:"-"`
	TerminalOutputFrame *TerminalOutputFrame `json:"-"`
	TerminalResizeFrame *TerminalResizeFrame `json:"-"`
	StreamCreditFrame   *StreamCreditFrame   `json:"-"`
	StreamCancelFrame   *StreamCancelFrame   `json:"-"`
	StreamOutcomeFrame  *StreamOutcomeFrame  `json:"-"`
}

type TerminalInputFrame struct {
	DataBase64 string `json:"dataBase64"`
	Sequence   int64  `json:"sequence"`
	Type       string `json:"type"`
}

type TerminalOutputFrame struct {
	DataBase64 string `json:"dataBase64"`
	Sequence   int64  `json:"sequence"`
	Type       string `json:"type"`
}

type TerminalResizeFrame struct {
	Columns  int    `json:"columns"`
	Rows     int    `json:"rows"`
	Sequence int64  `json:"sequence"`
	Type     string `json:"type"`
}

type TerminalSession struct {
	ExpiresAt          Timestamp    `json:"expiresAt"`
	Generation         int64        `json:"generation"`
	ID                 OpaqueID     `json:"id"`
	NextClientSequence int64        `json:"nextClientSequence"`
	SandboxID          OpaqueID     `json:"sandboxId"`
	State              SessionState `json:"state"`
	StreamWindowBytes  int64        `json:"streamWindowBytes"`
	Subprotocol        string       `json:"subprotocol"`
	WebsocketURL       string       `json:"websocketUrl"`
}

type Timestamp = time.Time

type TouchResult struct {
	Generation     int64     `json:"generation"`
	LastActivityAt Timestamp `json:"lastActivityAt"`
	SandboxID      OpaqueID  `json:"sandboxId"`
}

type UpdateRunnerPoolRequest struct {
	Architectures  RunnerArchitectureList `json:"architectures,omitempty"`
	Capabilities   RunnerCapabilityList   `json:"capabilities,omitempty"`
	CapacityPolicy RunnerCapacityPolicy   `json:"capacityPolicy,omitempty"`
	State          *RunnerPoolState       `json:"state,omitempty"`
}

type UpdateSandboxMetadataRequest struct {
	Metadata Metadata `json:"metadata"`
}

type UploadArtifactRequest struct {
	Content   string   `json:"content"`
	MediaType string   `json:"mediaType"`
	Metadata  Metadata `json:"metadata"`
	Name      string   `json:"name"`
	SHA256    string   `json:"sha256"`
}

type WaitSandboxRequest struct {
	DeadlineMilliseconds int64          `json:"deadlineMilliseconds"`
	States               []SandboxState `json:"states"`
}

type Workspace struct {
	CreatedAt  Timestamp `json:"createdAt"`
	Generation int64     `json:"generation"`
	ID         OpaqueID  `json:"id"`
	SizeBytes  int64     `json:"sizeBytes"`
	State      string    `json:"state"`
	UpdatedAt  Timestamp `json:"updatedAt"`
}

type WorkspacePath = string
