#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

required_variables=(
    SECONDBOX_CLIENT_IMAGE_ARTIFACT_VERSION
    SECONDBOX_CLIENT_IMAGE_BUNDLE_DIR
    SECONDBOX_CLIENT_IMAGE_KERNEL_PATH
    SECONDBOX_CLIENT_IMAGE_OUTPUT_REFERENCE
    SECONDBOX_CLIENT_IMAGE_PUBLIC_KEY
    SECONDBOX_CLIENT_IMAGE_PUBLIC_KEY_SHA256
    SECONDBOX_CLIENT_IMAGE_ROOTFS_SIZE_MIB
    SECONDBOX_CLIENT_IMAGE_ROOTFS_SOURCE_DIR
    SECONDBOX_CLIENT_IMAGE_ROOTFS_UUID
    SECONDBOX_CLIENT_IMAGE_SHARED_FORMAT
    SECONDBOX_CLIENT_IMAGE_SHARED_SIZE_MIB
    SECONDBOX_CLIENT_IMAGE_SIGNING_KEY
    SECONDBOX_CLIENT_IMAGE_SOURCE_COMMIT
    SECONDBOX_CLIENT_IMAGE_SOURCE_REFERENCE
)
for variable in "${required_variables[@]}"; do
    if [ -z "${!variable-}" ]; then
        echo "$variable is required" >&2
        exit 2
    fi
done
if [ "${SECONDBOX_CLIENT_IMAGE_KERNEL_CONFIG+x}" != x ]; then
    echo "SECONDBOX_CLIENT_IMAGE_KERNEL_CONFIG is required and may be empty" >&2
    exit 2
fi
if [ -e "$SECONDBOX_CLIENT_IMAGE_ROOTFS_SOURCE_DIR" ] || [ -e "$SECONDBOX_CLIENT_IMAGE_BUNDLE_DIR" ]; then
    echo "SecondBox client execution image output directories must not exist" >&2
    exit 2
fi

SECONDBOX_RUNNER_MICROVM_OCI_BASE_REFERENCE="$SECONDBOX_CLIENT_IMAGE_SOURCE_REFERENCE" \
SECONDBOX_RUNNER_MICROVM_OCI_MODE=prepared \
SECONDBOX_RUNNER_MICROVM_BROWSER_POLICY=forbid \
SECONDBOX_RUNNER_MICROVM_ROOTFS_SOURCE_DIR="$SECONDBOX_CLIENT_IMAGE_ROOTFS_SOURCE_DIR" \
SECONDBOX_RUNNER_MICROVM_SOURCE_COMMIT="$SECONDBOX_CLIENT_IMAGE_SOURCE_COMMIT" \
    "$repo_root/runner/scripts/microvm-image/rootfs/build-secondbox-rootfs-source.sh"

SECONDBOX_RUNNER_MICROVM_BUILD_KERNEL=false \
SECONDBOX_RUNNER_MICROVM_KERNEL_PATH="$SECONDBOX_CLIENT_IMAGE_KERNEL_PATH" \
SECONDBOX_RUNNER_MICROVM_KERNEL_CONFIG="$SECONDBOX_CLIENT_IMAGE_KERNEL_CONFIG" \
SECONDBOX_RUNNER_MICROVM_ARTIFACT_VERSION="$SECONDBOX_CLIENT_IMAGE_ARTIFACT_VERSION" \
SECONDBOX_RUNNER_MICROVM_SOURCE_COMMIT="$SECONDBOX_CLIENT_IMAGE_SOURCE_COMMIT" \
SECONDBOX_RUNNER_MICROVM_OUT_DIR="$SECONDBOX_CLIENT_IMAGE_BUNDLE_DIR" \
SECONDBOX_RUNNER_MICROVM_ROOTFS_SOURCE_DIR="$SECONDBOX_CLIENT_IMAGE_ROOTFS_SOURCE_DIR" \
SECONDBOX_RUNNER_MICROVM_SIGNING_KEY="$SECONDBOX_CLIENT_IMAGE_SIGNING_KEY" \
SECONDBOX_RUNNER_MICROVM_PUBLIC_KEY="$SECONDBOX_CLIENT_IMAGE_PUBLIC_KEY" \
SECONDBOX_RUNNER_MICROVM_PUBLIC_KEY_SHA256="$SECONDBOX_CLIENT_IMAGE_PUBLIC_KEY_SHA256" \
SECONDBOX_RUNNER_MICROVM_ROOTFS_SIZE_MIB="$SECONDBOX_CLIENT_IMAGE_ROOTFS_SIZE_MIB" \
SECONDBOX_RUNNER_MICROVM_SHARED_SIZE_MIB="$SECONDBOX_CLIENT_IMAGE_SHARED_SIZE_MIB" \
SECONDBOX_RUNNER_MICROVM_SHARED_FORMAT="$SECONDBOX_CLIENT_IMAGE_SHARED_FORMAT" \
SECONDBOX_RUNNER_MICROVM_ROOTFS_UUID="$SECONDBOX_CLIENT_IMAGE_ROOTFS_UUID" \
    "$repo_root/runner/scripts/microvm-image/build.sh"

docker build \
    --file "$repo_root/deploy/client-execution-image.Dockerfile" \
    --build-arg "ARTIFACT_VERSION=$SECONDBOX_CLIENT_IMAGE_ARTIFACT_VERSION" \
    --build-arg "SOURCE_REFERENCE=$SECONDBOX_CLIENT_IMAGE_SOURCE_REFERENCE" \
    --tag "$SECONDBOX_CLIENT_IMAGE_OUTPUT_REFERENCE" \
    "$SECONDBOX_CLIENT_IMAGE_BUNDLE_DIR"
