#!/usr/bin/env bash
set -Eeuo pipefail
caller_umask="$(umask)"
umask 077
repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"
fail() { echo "SecondBox qualification: $*" >&2; exit 1; }

wait_run() {
  local run="$1" status
  [[ "$run" =~ ^[0-9]{8}T[0-9]{6}-[0-9]+$ ]] || fail "invalid run ID"
  local directory="$repo_root/.tmp/qualify/$run"
  [[ -f "$directory/pid" ]] || fail "unknown run: $run"
  echo "Logs: $directory (tail -F $directory/*.log)"
  while [[ ! -f "$directory/result" ]]; do
    if ! kill -0 "$(cat "$directory/pid")" 2>/dev/null; then
      [[ -f "$directory/result" ]] || fail "supervisor stopped without a result; inspect $directory/supervisor.log"
    fi
    sleep 2
  done
  cat "$directory/timing.md"
  status="$(cat "$directory/result")"
  return "$status"
}

firecracker_release() {
  env -u SECONDBOX_SCENARIO_SHARD SECONDBOX_SCENARIO_COMPUTE_BACKEND=firecracker SECONDBOX_SCENARIO_RUNNER_PLACEMENT=compose SECONDBOX_SCENARIO_MODE=suite just test-scenario || return $?
  jq -e --arg commit "$source_commit" '.sourceCommit == $commit and .repositoryDirty == false' .tmp/scenario-qualification-evidence.json >/dev/null
}

sdk_packages() {
  # Packaging consumes the declarations produced by verify-generated.
  while [[ ! -f "$directory/verify-generated.status" ]]; do sleep 1; done
  local name code elapsed
  IFS=$'\t' read -r name code elapsed <"$directory/verify-generated.status"
  ((code == 0)) || { echo "SecondBox SDK package gate requires successful generated validation"; return 1; }
  just test-sdk-packages
}

stage() {
  local name="$1"; shift
  local start=$SECONDS status=0
  (umask "$caller_umask"; "$@") >"$directory/$name.log" 2>&1 || status=$?
  printf '%s\t%s\t%s\n' "$name" "$status" "$((SECONDS-start))" >"$directory/$name.status.tmp"
  mv "$directory/$name.status.tmp" "$directory/$name.status"
  return 0
}

worker() {
  directory="$1"
  # The environment file is private and generated by this command, never read from logs.
  source "$directory/environment"
  echo "$$" >"$directory/pid.tmp"
  mv "$directory/pid.tmp" "$directory/pid"
  exec 9>"$repo_root/.tmp/qualify/checkout.lock"
  flock -n 9 || fail "another qualification owns this checkout"
  local start=$SECONDS status=0 name code elapsed
  if [[ "$tier" == release ]]; then
    [[ "$(git rev-parse HEAD)" == "$source_commit" && -z "$(git status --porcelain --untracked-files=all)" ]] || fail "release source changed after preflight"
  fi
  local -a jobs=()
  if [[ "$only" == all || "$only" == gates ]]; then
    # Cached diagnostics contain source paths; do not share them across worktrees.
    export GOLANGCI_LINT_CACHE="$repo_root/.tmp/golangci-lint"
    for name in verify-generated test test-contract test-compose test-image-policy test-sdk-packages test-deployment test-install-docs test-release-workflow lint; do
      if [[ "$name" == test-sdk-packages ]]; then
        stage "$name" sdk_packages & jobs+=("$!")
      else
        stage "$name" just "$name" & jobs+=("$!")
      fi
    done
  fi
  if [[ "$only" == all || "$only" == firecracker ]]; then
    if [[ "$tier" == release ]]; then
      stage firecracker firecracker_release & jobs+=("$!")
    else
      for ((i=1; i<=QUALIFY_FIRECRACKER_SHARDS; i++)); do
        stage "firecracker-$i" env SECONDBOX_SCENARIO_SHARD="$i/$QUALIFY_FIRECRACKER_SHARDS" SECONDBOX_SCENARIO_COMPUTE_BACKEND=firecracker SECONDBOX_SCENARIO_RUNNER_PLACEMENT=compose SECONDBOX_SCENARIO_MODE=suite just test-scenario & jobs+=("$!")
      done
    fi
  fi
  if [[ "$only" == gvisor || ( "$only" == all && "$tier" == release ) ]]; then
    stage gvisor scripts/qualify-gvisor.sh "$directory" "$source_commit" & jobs+=("$!")
  fi
  for job in "${jobs[@]}"; do wait "$job" || status=1; done
  if [[ "$tier" == release ]] && { [[ "$(git rev-parse HEAD)" != "$source_commit" ]] || [[ -n "$(git status --porcelain --untracked-files=all)" ]]; }; then
    printf 'source-integrity\t1\t0\n' >"$directory/source-integrity.status"
  fi
  {
    printf '| Stage | Result | Wall clock |\n|---|---|---|\n'
    for file in "$directory"/*.status; do
      IFS=$'\t' read -r name code elapsed <"$file"
      if ((code == 0)); then result=PASS; else result="FAIL ($code)"; status=1; fi
      printf '| %s | %s | %sm %ss |\n' "$name" "$result" "$((elapsed/60))" "$((elapsed%60))"
    done
    elapsed=$((SECONDS-start))
    printf '| Total | %s | %sm %ss |\n' "$([[ $status == 0 ]] && echo PASS || echo FAIL)" "$((elapsed/60))" "$((elapsed%60))"
  } >"$directory/timing.md"
  cat "$directory/timing.md"
  printf '%s\n' "$status" >"$directory/result.tmp"
  mv "$directory/result.tmp" "$directory/result"
}

if [[ "${1:-}" == --worker ]]; then worker "$2"; exit; fi
if [[ "${1:-}" == --wait ]]; then [[ $# == 2 ]] || fail 'usage: --wait RUN'; wait_run "$2"; exit; fi
tier=pr only=all
while (($#)); do
  case "$1" in
    --tier|--only) [[ $# -ge 2 ]] || fail "missing value for $1"; printf -v "${1#--}" '%s' "$2"; shift 2 ;;
    --help) echo 'Usage: just qualify [--tier pr|release] [--only gates|firecracker|gvisor] | --wait RUN'; exit 0 ;;
    *) fail "unknown argument: $1" ;;
  esac
done
[[ "$tier" == pr || "$tier" == release ]] || fail 'tier must be pr or release'
[[ "$only" == all || "$only" == gates || "$only" == firecracker || "$only" == gvisor ]] || fail 'only must be gates, firecracker, or gvisor'
config="${HOME:?}/.config/secondbox/qualify.env"
[[ -f "$config" ]] || fail "copy deploy/qualify.env.example to $config and configure it"
bash -n "$config" || fail "invalid environment file: $config"
set -a
source "$config"
set +a
export QUALIFY_FIRECRACKER_SHARDS="${QUALIFY_FIRECRACKER_SHARDS:-4}"
[[ "$QUALIFY_FIRECRACKER_SHARDS" =~ ^[1-9][0-9]*$ ]] && ((QUALIFY_FIRECRACKER_SHARDS <= 64)) || fail 'QUALIFY_FIRECRACKER_SHARDS must be 1..64'
for tool in git just go flock setsid; do command -v "$tool" >/dev/null || fail "missing tool: $tool"; done
if [[ "$tier" == release ]]; then
  [[ -z "$(git status --porcelain --untracked-files=all)" ]] || fail 'release tier requires a clean tree (including untracked files)'
fi
if [[ "$only" == all || "$only" == gates ]]; then
  : "${SECONDBOX_TEST_DATABASE_URL:?set SECONDBOX_TEST_DATABASE_URL to a disposable PostgreSQL database}"
  [[ "$SECONDBOX_TEST_DATABASE_URL" =~ ^postgres(ql)?:// ]] || fail 'invalid test PostgreSQL URL'
  for tool in npm jq docker rg golangci-lint; do command -v "$tool" >/dev/null || fail "missing tool: $tool"; done
  [[ -x node_modules/.bin/tsc ]] || fail 'run npm ci --ignore-scripts first'
fi
if [[ "$only" == all || "$only" == firecracker ]]; then
  for key in SECONDBOX_SCENARIO_MICROVM_ARTIFACTS_DIR SECONDBOX_RUNNER_ARTIFACT_PUBLIC_KEY SECONDBOX_RUNNER_WORKSPACE_ROOT; do
    [[ "${!key:-}" == /* && -e "${!key}" ]] || fail "$key must be an existing absolute path"
  done
  [[ -d "$SECONDBOX_SCENARIO_MICROVM_ARTIFACTS_DIR" && -d "$SECONDBOX_RUNNER_WORKSPACE_ROOT" && -f "$SECONDBOX_RUNNER_ARTIFACT_PUBLIC_KEY" ]] || fail 'invalid Firecracker input paths'
  [[ "${SECONDBOX_RUNNER_ARTIFACT_PUBLIC_KEY_SHA256:-}" =~ ^[a-f0-9]{64}$ ]] || fail 'invalid artifact key fingerprint'
  for tool in openssl sha256sum docker; do command -v "$tool" >/dev/null || fail "missing tool: $tool"; done
  actual="$(openssl pkey -pubin -in "$SECONDBOX_RUNNER_ARTIFACT_PUBLIC_KEY" -outform DER | sha256sum | cut -d' ' -f1)"
  [[ "$actual" == "$SECONDBOX_RUNNER_ARTIFACT_PUBLIC_KEY_SHA256" ]] || fail 'artifact public key fingerprint mismatch'
  for key in SECONDBOX_SCENARIO_RUNTIME_BUNDLE_DIGEST SECONDBOX_SCENARIO_TOOLCHAIN_BUNDLE_DIGEST; do
    [[ "${!key:-}" =~ ^sha256:[a-f0-9]{64}$ ]] || fail "$key must be a sha256 digest"
  done
  [[ "${SECONDBOX_REQUIRE_QUALIFIED_SCENARIO:-}" == 1 ]] || fail 'SECONDBOX_REQUIRE_QUALIFIED_SCENARIO must be 1'
  [[ -c /dev/kvm && -c /dev/net/tun ]] || fail 'Firecracker requires /dev/kvm and /dev/net/tun'
  docker info >/dev/null || fail 'Docker unavailable'
fi
if [[ "$only" == gvisor || ( "$only" == all && "$tier" == release ) ]]; then
  scripts/qualify-gvisor.sh --preflight
fi
source_commit="$(git rev-parse HEAD)"
run="$(date -u +%Y%m%dT%H%M%S)-$$"
directory="$repo_root/.tmp/qualify/$run"
mkdir -p "$directory"
{ export -p; declare -p tier only source_commit caller_umask; } >"$directory/environment"
echo "Qualification run: $run ($tier, $only, $source_commit)"
if command -v systemd-run >/dev/null && systemctl --user show-environment >/dev/null 2>&1; then
  systemd-run --user --unit="secondbox-suite-qualify-$run" --collect \
    --property="WorkingDirectory=$repo_root" --property="StandardOutput=file:$directory/supervisor.log" \
    --property=StandardError=inherit --setenv="PATH=$PATH" --setenv="HOME=$HOME" \
    /bin/bash "$repo_root/scripts/qualify.sh" --worker "$directory"
else
  setsid /bin/bash "$repo_root/scripts/qualify.sh" --worker "$directory" >"$directory/supervisor.log" 2>&1 < /dev/null &
fi
for ((attempt=0; attempt<50; attempt++)); do [[ -f "$directory/pid" ]] && break; sleep 0.1; done
wait_run "$run"
