#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

: "${SECONDBOX_RELEASE_QUALIFICATION_CANDIDATE_DIRECTORY:?SecondBox packaged KVM qualification requires SECONDBOX_RELEASE_QUALIFICATION_CANDIDATE_DIRECTORY}"
: "${SECONDBOX_RELEASE_QUALIFICATION_SUBJECT_MANIFEST:?SecondBox packaged KVM qualification requires SECONDBOX_RELEASE_QUALIFICATION_SUBJECT_MANIFEST}"
: "${SECONDBOX_RELEASE_QUALIFICATION_HOSTS_FILE:?SecondBox packaged KVM qualification requires SECONDBOX_RELEASE_QUALIFICATION_HOSTS_FILE}"
: "${SECONDBOX_RELEASE_QUALIFICATION_CONTROLLER_DIRECTORY:?SecondBox packaged KVM qualification requires SECONDBOX_RELEASE_QUALIFICATION_CONTROLLER_DIRECTORY}"
: "${SECONDBOX_RELEASE_QUALIFICATION_OUTPUT_DIRECTORY:?SecondBox packaged KVM qualification requires SECONDBOX_RELEASE_QUALIFICATION_OUTPUT_DIRECTORY}"

exec node "$repo_root/scripts/run-packaged-release-qualification.mjs" \
  "$SECONDBOX_RELEASE_QUALIFICATION_CANDIDATE_DIRECTORY" \
  "$SECONDBOX_RELEASE_QUALIFICATION_SUBJECT_MANIFEST" \
  "$SECONDBOX_RELEASE_QUALIFICATION_HOSTS_FILE" \
  "$SECONDBOX_RELEASE_QUALIFICATION_CONTROLLER_DIRECTORY" \
  "$SECONDBOX_RELEASE_QUALIFICATION_OUTPUT_DIRECTORY" \
  kvm
