#!/usr/bin/env bash
set -Eeuo pipefail
umask 077

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

if [[ "${SECONDBOX_REQUIRE_QUALIFIED_STRESS:-}" != "1" ]]; then
  echo "SECONDBOX_REQUIRE_QUALIFIED_STRESS must be 1" >&2
  exit 1
fi
for variable in SECONDBOX_STRESS_CONFIG SECONDBOX_STRESS_OUTPUT; do
  if [[ -z "${!variable:-}" ]]; then
    echo "SecondBox stress qualification missing required variable: $variable" >&2
    exit 1
  fi
done
command -v jq >/dev/null 2>&1 ||
  {
    echo "SecondBox stress qualification prerequisite missing: jq" >&2
    exit 1
  }

if [[ "$SECONDBOX_STRESS_CONFIG" != /* ||
      -L "$SECONDBOX_STRESS_CONFIG" ||
      ! -f "$SECONDBOX_STRESS_CONFIG" ]]; then
  echo "SECONDBOX_STRESS_CONFIG must be an absolute regular non-symbolic-link file" >&2
  exit 1
fi
if [[ "$SECONDBOX_STRESS_OUTPUT" != /* ||
      -e "$SECONDBOX_STRESS_OUTPUT" ||
      -L "$SECONDBOX_STRESS_OUTPUT" ]]; then
  echo "SECONDBOX_STRESS_OUTPUT must be an absent absolute path" >&2
  exit 1
fi
output_parent="$(dirname "$SECONDBOX_STRESS_OUTPUT")"
if [[ -L "$output_parent" || ! -d "$output_parent" ]]; then
  echo "SECONDBOX_STRESS_OUTPUT parent must be an existing non-symbolic-link directory" >&2
  exit 1
fi

go run ./tests/scenario/stress \
  --mode validate \
  --config "$SECONDBOX_STRESS_CONFIG"

export SECONDBOX_REQUIRE_QUALIFIED_SCENARIO=1
export SECONDBOX_SCENARIO_MODE=stress
export SECONDBOX_RUNNER_ID=secondbox-stress-runner
export SECONDBOX_RUNNER_POOL_ID
SECONDBOX_RUNNER_POOL_ID="$(jq -er '.runnerPoolName' "$SECONDBOX_STRESS_CONFIG")"

export SECONDBOX_SCENARIO_SUBJECT_MAX_SANDBOXES
SECONDBOX_SCENARIO_SUBJECT_MAX_SANDBOXES="$(jq -er '.subjectMaxSandboxes' "$SECONDBOX_STRESS_CONFIG")"
export SECONDBOX_SCENARIO_SUBJECT_MAX_ACTIVE_INSTANCES
SECONDBOX_SCENARIO_SUBJECT_MAX_ACTIVE_INSTANCES="$(jq -er '.subjectMaxActiveInstances' "$SECONDBOX_STRESS_CONFIG")"
export SECONDBOX_SCENARIO_SUBJECT_MAX_CONCURRENT_OPERATIONS
SECONDBOX_SCENARIO_SUBJECT_MAX_CONCURRENT_OPERATIONS="$(jq -er '.subjectMaxConcurrentOperations' "$SECONDBOX_STRESS_CONFIG")"
export SECONDBOX_SCENARIO_SUBJECT_MAX_SNAPSHOTS
SECONDBOX_SCENARIO_SUBJECT_MAX_SNAPSHOTS="$(jq -er '.subjectMaxSnapshots' "$SECONDBOX_STRESS_CONFIG")"
export SECONDBOX_SCENARIO_SUBJECT_MAX_ARTIFACT_BYTES
SECONDBOX_SCENARIO_SUBJECT_MAX_ARTIFACT_BYTES="$(jq -er '.subjectMaxArtifactBytes' "$SECONDBOX_STRESS_CONFIG")"
export SECONDBOX_SCENARIO_SUBJECT_MAX_ARTIFACTS
SECONDBOX_SCENARIO_SUBJECT_MAX_ARTIFACTS="$(jq -er '.subjectMaxArtifacts' "$SECONDBOX_STRESS_CONFIG")"
export SECONDBOX_SCENARIO_SUBJECT_MAX_PORT_SESSIONS
SECONDBOX_SCENARIO_SUBJECT_MAX_PORT_SESSIONS="$(jq -er '.subjectMaxPortSessions' "$SECONDBOX_STRESS_CONFIG")"
export SECONDBOX_SCENARIO_SUBJECT_MAX_CPU_MILLIS
SECONDBOX_SCENARIO_SUBJECT_MAX_CPU_MILLIS="$(jq -er '.subjectMaxCpuMillis' "$SECONDBOX_STRESS_CONFIG")"
export SECONDBOX_SCENARIO_SUBJECT_MAX_MEMORY_BYTES
SECONDBOX_SCENARIO_SUBJECT_MAX_MEMORY_BYTES="$(jq -er '.subjectMaxMemoryBytes' "$SECONDBOX_STRESS_CONFIG")"

export SECONDBOX_SCENARIO_STORAGE_RECOVERY_PERCENT
SECONDBOX_SCENARIO_STORAGE_RECOVERY_PERCENT="$(jq -er '.runner.storagePressureRecoveryPercent' "$SECONDBOX_STRESS_CONFIG")"
export SECONDBOX_SCENARIO_STORAGE_WARNING_PERCENT
SECONDBOX_SCENARIO_STORAGE_WARNING_PERCENT="$(jq -er '.runner.storagePressureWarningPercent' "$SECONDBOX_STRESS_CONFIG")"
export SECONDBOX_SCENARIO_STORAGE_DENY_PERCENT
SECONDBOX_SCENARIO_STORAGE_DENY_PERCENT="$(jq -er '.runner.storagePressureAdmissionDenyPercent' "$SECONDBOX_STRESS_CONFIG")"
export SECONDBOX_SCENARIO_SANDBOX_MAX_VCPUS
SECONDBOX_SCENARIO_SANDBOX_MAX_VCPUS="$(jq -er '.runner.sandboxMaxVcpus' "$SECONDBOX_STRESS_CONFIG")"
export SECONDBOX_SCENARIO_SANDBOX_MEMORY_MIB
SECONDBOX_SCENARIO_SANDBOX_MEMORY_MIB="$(jq -er '.runner.sandboxMemoryMiB' "$SECONDBOX_STRESS_CONFIG")"
export SECONDBOX_SCENARIO_SANDBOX_DISK_MIB
SECONDBOX_SCENARIO_SANDBOX_DISK_MIB="$(jq -er '.runner.sandboxDiskMiB' "$SECONDBOX_STRESS_CONFIG")"
export SECONDBOX_SCENARIO_MEMORY_BUDGET_MIB
SECONDBOX_SCENARIO_MEMORY_BUDGET_MIB="$(jq -er '.runner.memoryBudgetMiB' "$SECONDBOX_STRESS_CONFIG")"
export SECONDBOX_SCENARIO_MAX_CONCURRENT_PER_SANDBOX
SECONDBOX_SCENARIO_MAX_CONCURRENT_PER_SANDBOX="$(jq -er '.runner.maxConcurrentPerSandbox' "$SECONDBOX_STRESS_CONFIG")"
export SECONDBOX_SCENARIO_MAX_CONCURRENT_GLOBAL
SECONDBOX_SCENARIO_MAX_CONCURRENT_GLOBAL="$(jq -er '.runner.maxConcurrentGlobal' "$SECONDBOX_STRESS_CONFIG")"
export SECONDBOX_SCENARIO_FILE_TRANSFER_MAX_BYTES
SECONDBOX_SCENARIO_FILE_TRANSFER_MAX_BYTES="$(jq -er '.runner.fileTransferMaxBytes' "$SECONDBOX_STRESS_CONFIG")"

export SECONDBOX_SCENARIO_HTTP_TIMEOUT_SECONDS=70
export SECONDBOX_SCENARIO_ASSIGNMENT_CLAIM_MILLISECONDS=30000
export SECONDBOX_SCENARIO_ASSIGNMENT_DEADLINE_MILLISECONDS=120000
export SECONDBOX_SCENARIO_RUNNER_HEARTBEAT_TIMEOUT_MILLISECONDS=30000

exec "$repo_root/scripts/test-scenario.sh"
